### ISSUE TITLE
Cheating via spoiler log is still possible

### ISSUE THREAD

**Issue by cmacmillan** [AmazingAmpharos/OoT-Randomizer#100]
A user could potentially circumvent the spoiler log seed randomization by simply commenting out lines 34-37 of Main.py and then launching the app normally.

**Comment by AlissonPQ** [comment]
I was about to post it today, as I found out about this "anti-cheating strategy". Since the software is open source, it is pointless to do it. It is just creating an inconvenience for people who change their minds about the spoiler and want to generate it.

**Comment by CMuncey** [comment]
Race ROMS are generated using the release version, which is an executable instead of Python source code. I believe the ROMS are also generated by a proctor and distributed, but I'm not sure about that. I've noticed that in the races I've watched so far, everyone has the same tunic/navi colors, and I doubt that's just a coincidence.

**Comment by AlissonPQ** [comment]
The point is, anyone can download the generator, alter it, compile it, and get the spoilers for any given seed. When the code invokes random.seed(world.seed), it is simply passing the seed entered by the user to a sha512 function and generating another seed.

The right way to prevent cheating is to prevent people from knowing what is the seed when they generate a ROM with spoiler log. In other words, when spoiler log is checked, the output file will NOT contain the seed in its name. The seed is secret.

**Comment by AlissonPQ** [comment]
Well, I might as well just fork this randomizer and release a "jailbreak" version then, so that everyone can generate the spoiler for any seed they are struggling to complete.

**Comment by CMuncey** [comment]
I would imagine that many people made forks before that feature was added, it was only added a little before the release of 2.0.. And the new dev branch seems to have updated the seed generation anyway.

Cheating is still easily possible, but if a runner is caught cheating, they'll probably get banned from further races pretty quick

**Comment by flagrama** [comment]
It is just a deterrent to keep race cheating from being a matter of "Oh I'll just check this button and have all the answers." Most races have someone making the ROM and sharing it with others without any settings or the seed anyway (and also generating a spoiler log to find logic issues later if something goes wrong) So currently it's a non-issue anyway.

**Comment by rlbond86** [comment]
Someone could also just use a tool to read the rom directly and figure out what's inside every chest.

**Comment by AmazingAmpharos** [comment]
It's easy to cheat yes, and there's not a good solution to make that not true. The logic here is just making it just barely hard enough that completely non-technical users won't be able to cheat which is actually a pretty large percentage of the playerbase. For tournaments, the seed would be generated by a third party and the seed number not publicly shared; even then ROM inspection would be pretty easy to do if you actually knew what you were doing, but hey, it's not like the N64 is a platform with real security...
