### ISSUE TITLE
Pause Crash on Retroarch

### ISSUE THREAD

**Issue by ThamanVelasquezBice** [AmazingAmpharos/OoT-Randomizer#101]
I am not 100% sure if this belongs as a github issue, but pausing on Retroarch in areas that have more than a few objects rendered causes a crash ~90% of the time. If it is an issue in my configuration could someone possibly let me know what their configuration is? 

The N64 core I am using is MupenN64

**Comment by CMuncey** [comment]
Did you compress the rom when generating the seed?

**Comment by bwarren97** [comment]
I have the same issue, running Mupen64 on Android. Often times going to the pause screen crashes the emulator, dumping my progress since the last time I saved. I can easily save state before accessing the menu, but that makes it a tad bit tedious any time I have to switch items.

I did not compress the ROM when generating

**Comment by flagrama** [comment]
You MUST compress the ROM if you play it on an emulator. If you do not, it crashes while pausing.

**Comment by bwarren97** [comment]
Interesting, I wonder why that is

**Comment by bwarren97** [comment]
Interesting, I wonder why that is

**Comment by ThamanVelasquezBice** [comment]
I apologize for not responding sooner. I did compress my rom when generating the seed, but still often had this issue(this was my second seed as I did not compress the first). I switched to Bizhawk and this emulator did not have the same issue, so I am wondering if it might be specifically related to Retroarch.

**Comment by CMuncey** [comment]
You also need to make sure to run the correct rom after you compress. The 2.0 release will give you two roms, one with `-comp.z64` at the end, and one without. The one without it is the decompressed rom, which will cause crashing.

**Comment by ThamanVelasquezBice** [comment]
Okay, next time I do a randomizer(probably in a couple of days) I will try it out
