### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by NaviHater** [AmazingAmpharos/OoT-Randomizer#102]
I finally got the GUI working, so I selected my preferences, hit the "randomize" button, and nothing happens.  

(Mac OSX El Capitan, python 3.7)

Any Ideas?

**Comment by flagrama** [comment]
Do you have a screenshot of the randomizer right after or right before you click the randomize button?

**Comment by NaviHater** [comment]
![screen shot 2018-08-29 at 5 09 23 pm](https://user-images.githubusercontent.com/42723903/44818327-57c53000-abae-11e8-8b36-f315306cd074.png)

**Comment by flagrama** [comment]
You need to download a v1.0 U Ocarina of Time ROM and use the Select Rom button to choose it. Also make sure you check "Compress patched Rom" or else it will crash while pausing if you try to play it on an emulator.

**Comment by NaviHater** [comment]
Do I have to put a seed #?

**Comment by NaviHater** [comment]
It's still not working
![screen shot 2018-08-29 at 5 26 17 pm](https://user-images.githubusercontent.com/42723903/44819024-c86d4c00-abb0-11e8-8a8a-1bb9de19223c.png)

**Comment by flagrama** [comment]
Are you running it from the Terminal? Does it have any errors listed in the Terminal window? It's not just "frozen" right? The compressor will use 100% of your CPU for a while and make the app look unresponsive. Lastly, does clicking "Open Output Directory" bring up a Finder window and are there any OoT_medallions[...]-comp.z64 files?

**Comment by flagrama** [comment]
Wait, you're not clicking the Tab at the top are you? You're clicking the "Generate Patched Rom" button, right?

**Comment by NaviHater** [comment]
Do I press generate patched rom?

**Comment by flagrama** [comment]
Yes.

**Comment by NaviHater** [comment]
I don't know what you mean, but it it has those medallion things

**Comment by NaviHater** [comment]
so which file is the rom?

**Comment by flagrama** [comment]
In the output directory there should be a ROM called OoT_`bridgereq`\_`options`\_`seednumber`-comp.z64
In your case it should be something like OoT_medallions_openforest_opendoor_beatableonly_1231554656-comp.z64

Personally I recommend not using beatable only as it will lock you out of locations and can be confusing for newcomers, regardless, that should be right about the correct file name.

**Comment by NaviHater** [comment]
the "beatable not all items accessible" was an accident and i unchecked it, but thanks for the advice.

I found the rom and thanks for all your help
