### ISSUE TITLE
Fire Temple issue

### ISSUE THREAD

**Issue by LasseOmen** [AmazingAmpharos/OoT-Randomizer#103]
Seed 893473467 
Open door, forest. Beatable. Dungeon items.

I may be being dumb here. I'm to the point 3f flame walls and boulders, the pillar to hammer down etc. Needing a key for the door to the center here, but lacking it. Map, compass in hand. 3 chests ahead of me in dungeon. Not sure if I'm forgetting something or stuck.

**Comment by flagrama** [comment]
It is likely Volvagia has a Small Key. If you have the Boss Key you can reach her room with Hover Boots. As long as you have the Boss Key at this point you are expected to find Hover Boots somewhere you've missed.

**Comment by LasseOmen** [comment]
I do not have boss key either. :/

**Comment by flagrama** [comment]
Do you have hammer? Did you do the rooms behind the hammerable blocks in the entrance where vanilla boss key is? Did you check both vanilla Map chest and vanilla Compass chest?

**Comment by flagrama** [comment]
Do you have a spoiler log? If not do you have the seed, file name?

**Comment by LasseOmen** [comment]
Oot_medallions-openforest-opendoor_893473467.z64. 

how do I access spoiler log?

**Comment by flagrama** [comment]
You have to generate it while generating the seed as generating one later changes the item placement.

I am slightly confused. Your initial settings imply you have beatable only, but your file name indicates you don't. Which is it?

In this case it doesn't matter as both create the same exact Fire Temple layout:
> Fire Temple Chest Near Boss: Small Key (Fire Temple)
Fire Temple Fire Dancer Chest: Small Key (Fire Temple)
Fire Temple Boss Key Chest: Map (Fire Temple)
Fire Temple Big Lava Room Bombable Chest: Rupees (5)
Fire Temple Big Lava Room Open Chest: Small Key (Fire Temple)
Volvagia Heart: Small Key (Fire Temple)
Fire Temple Boulder Maze Lower Chest: Small Key (Fire Temple)
Fire Temple Boulder Maze Upper Chest: Slingshot
Fire Temple Boulder Maze Side Room: Small Key (Fire Temple)
Fire Temple Boulder Maze Bombable Pit: Compass (Fire Temple)
Fire Temple Scarecrow Chest: Ice Trap
Fire Temple Map Chest: Small Key (Fire Temple)
Fire Temple Compass Chest: Bombs (10)
Fire Temple Highest Goron Chest: Small Key (Fire Temple)
Fire Temple Megaton Hammer Chest: Boss Key (Fire Temple)

Did you miss any of them in particular?
