### ISSUE TITLE
go to pause menu and the whole game gets all jumbled colours

### ISSUE THREAD

**Issue by declanq13** [AmazingAmpharos/OoT-Randomizer#106]
as soon as you press the pause button the whole screen textures change to all different colours and you have to restart but it just does the same thing.

**Comment by declanq13** [comment]
on retroarch

**Comment by flagrama** [comment]
Did you compress your rom? If not, you must compress it if you are going to play on an emulator.

**Comment by declanq13** [comment]
yes

**Comment by declanq13** [comment]
i did

**Comment by flagrama** [comment]
You can edit github comments btw.

I recommend heading to the #questions-setup section of the discord and asking for help there: https://discord.gg/225jUC
