### ISSUE TITLE
On a Mac!!

### ISSUE THREAD

**Issue by JVLawnDarts** [AmazingAmpharos/OoT-Randomizer#107]
I know macs are not really meant for this kind of stuff but I have a new MBP w/ touch bar and have no clue what I'm doing... I have python, oot v1.0.rar, the current version of the randomizer, and OpenEmu... Please help!!

**Comment by flagrama** [comment]
https://github.com/AmazingAmpharos/OoT-Randomizer/issues/96
https://github.com/AmazingAmpharos/OoT-Randomizer/issues/102
Let me know if these don't help solve your problems.
