### ISSUE TITLE
Dev Branch

### ISSUE THREAD

**Issue by tommaniacal** [AmazingAmpharos/OoT-Randomizer#111]
How does one go about downloading this version of the randomizer? I don't have Python, so I've been using the exe version of it. Does the dev branch require Python? I'm new to using github so pardon my stupid questions

**Comment by etaylor8086** [comment]
For the dev branch of the randomizer, I believe you need at least version 3.5 of Python installed on your machine.

Afterwards, you can download a zip of the latest Dev code by going to this link: https://github.com/AmazingAmpharos/OoT-Randomizer/archive/Dev.zip

Unzip that file, then double click the Gui.py file.

**Comment by etaylor8086** [comment]
For faster (but more experimental) builds of the Dev branch, you can find them on Testrunner's fork of the randomizer:

https://github.com/TestRunnerSRL/OoT-Randomizer/archive/Dev.zip

**Comment by flagrama** [comment]
You need at least version 3.6 of Python installed for any version of the randomizer 2.0 and above. The readme has the incorrect version provided.

**Comment by etaylor8086** [comment]
@flagrama Good catch, I updated my comment accordingly.
