### ISSUE TITLE
WinError 216: This version is not compatible

### ISSUE THREAD

**Issue by ReptileGaming** [AmazingAmpharos/OoT-Randomizer#112]
I can open and use the randomizer program just fine, and the base rom works well with Project64, but when I attempt to create patched rom, it gives me the following error message:

[WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software's publisher

From google searches it looks like it has something to do with x64 and x32 versions of different programs, but how would I determine what to do to fix it?

**Comment by flagrama** [comment]
You are running a 32-bit version of Windows. [This Dev version](https://github.com/TestRunnerSRL/OoT-Randomizer/tree/Dev) has 32 bit versions of the compressor and decompressor, but you'll need to install Python 3.6 or higher to run it.

**Comment by ChrisMuncey** [comment]
Or you could just steal the `Decompress32.exe` and `Compress32.exe` and put them in your normal Decompress and Compress folder, and then rename them to `Decompress.exe` and `Compress.exe`

**Comment by Ethan2121** [comment]
Ive tried these solutions and have the same problem. However it still does the same thing and doesn't work

**Comment by Ethan2121** [comment]
where is the original files?

**Comment by ChrisMuncey** [comment]
The original files for what?

**Comment by Ethan2121** [comment]
Where do we steel Decompress 32.exe and Compress 32.exe from?

**Comment by CMuncey** [comment]
You can get them from the Dev branch [here](https://github.com/AmazingAmpharos/OoT-Randomizer/tree/Dev), just download it, and then take the files to replace yours

**Comment by Ethan2121** [comment]
Thank you so much it works now
