### ISSUE TITLE
Possible softlock?

### ISSUE THREAD

**Issue by Greenmetroid** [AmazingAmpharos/OoT-Randomizer#113]
I'm doing a seed where I got some really nice key items, but I'm having trouble progressing.  I desperately need bombs to open hella doors, but I found bombchus (5) in bottom of the well.  It seems there's only a couple places to get bombchus, neither of which I can get to (bombchu shop as child vacant until I have bombs.  Magic carpet as an adult is impossible without hover boots, or bombs to do a bomb jump).  I haven't exhausted all possibilities of progress, but it's getting nigh, and they keep giving me bloopies.  I'll post my seed later, but is it possible that bombchus can be a requirement to progress, but if you waste em, you can't progress?

**Comment by flagrama** [comment]
In version 2.0 bombchus are never required. In Dev or the TestRunner fork there is an option to put bombchus into logic, but it opens up the bombchu shop and bombchu bowling when you find your first bombchus so you can never run out of them completely.
