### ISSUE TITLE
 Quirks to Know : Fire temple 

### ISSUE THREAD

**Issue by MangeMonPain** [AmazingAmpharos/OoT-Randomizer#115]
Quirks to Know

""" -In the Fire Temple, you can reach the Boss Key door from the beginning with Hover Boots. """""

how it is possible to do that ? some1 can explain pls ?

**Comment by flagrama** [comment]
Go to where the goron cell is, put on hover boots. Run.

**Comment by MangeMonPain** [comment]
i thought it was the place where the boss key is. My bad
