### ISSUE TITLE
Windmill Softlock

### ISSUE THREAD

**Issue by STQZ** [AmazingAmpharos/OoT-Randomizer#116]
I went to the windmill and played the song of storms to access the BotW, but the game softlocked. I believe this only happens when trying to open the well at night. I waited until daytime, and the well opened properly after playing the song.

**Comment by flagrama** [comment]
This is a known issue with Project 64 and is one of the many reasons PJ64 is not recommended to use at all.

**Comment by Stevemaster92** [comment]
Leaving and entering the windmill solved this issue for me.
