### ISSUE TITLE
Spoiler Log doesn't match in-game items

### ISSUE THREAD

**Issue by tommaniacal** [AmazingAmpharos/OoT-Randomizer#119]
It says that the adult shooting gallery gives me the Nocturne of Shadow, however it gave me 50 rupees instead. I need to beat the shadow temple to get the light medallion, so this is an issue
[OoT_HJVBPMA69DAUB_LSPPSHBSJ2_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2354224/OoT_HJVBPMA69DAUB_LSPPSHBSJ2_Spoiler.txt)

**Comment by flagrama** [comment]
You need the Bow to get the actual prize from the shooting gallery. If you don't have a Bow you can only play to win the 50 rupees.

**Comment by tommaniacal** [comment]
Oh okay duh. Thanks!
