### ISSUE TITLE
Requirements for Gerudo Valley Unclear

### ISSUE THREAD

**Issue by Laugh10704** [AmazingAmpharos/OoT-Randomizer#123]
Hello, love the OOT randomizer - thank you so much for putting it together.

This is the first time playing the randomizer and I realized a dozen or so hours through my playthrough that I was unable to proceed. After checking the spoiler sheet, I realized that the randomizer was expecting me to go to Gerudo Valley / Spirit Temple with only the hookshot in hand.

Looking online it looks like it's possible, but I wish it would have been more clear that this was an expected possibility. I think either updating the description (or maybe even an option to require longshot?) would be great, so people like me (who aren't big on glitching through the game) don't feel like they're stuck.

My seed is 373918057 and the spoiler is attached.

[OoT_dungeons-openforest-opendoor-fastganon-beatableonly_373918057_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2359419/OoT_dungeons-openforest-opendoor-fastganon-beatableonly_373918057_Spoiler.txt)

Thank you!

**Comment by emerald000** [comment]
The randomizer expects you to use the longshot or the hover boots to go through the desert sand pit.

**Comment by Laugh10704** [comment]
Actually, I just realized that epona can jump over the gerudo valley hole. Man do I feel silly. Honestly I don't remember ever doing that, but I guess it's just been a while. Nevermind, and again thank you for the awesome randomizer!
