### ISSUE TITLE
Where's the correct version?

### ISSUE THREAD

**Issue by Jarrodmclagit** [AmazingAmpharos/OoT-Randomizer#125]
It says that I need a specific rom to use the randomizer, yet I've found no where saying anything about which one I need in particular except for "The Legend of Zelda: Ocarina of Time version 1.0 NTSC-US version", which when I would search that, I'm entering a lottery to see which of these bajillion roms is the right one. Can anyone link me to where the correct version is hiding?

**Comment by flagrama** [comment]
CRC EC95702D

**Comment by Jarrodmclagit** [comment]
What

**Comment by flagrama** [comment]
http://lmgtfy.com/?q=EC95702D

**Comment by Jarrodmclagit** [comment]
That doesn't help nob-head
(Sorry, I was in a bad mood while searching at the time, I didn't mean anything by it)

**Comment by flagrama** [comment]
1) It is literally the first result
2) We can't just link to pirated content.

**Comment by etaylor8086** [comment]
Insulting people who literally are working on this for free isn't the best idea.

Also, it's spelled "knob-head".
