### ISSUE TITLE
Unfinishable seed Song of time and Water temple

### ISSUE THREAD

**Issue by BenoitGeslain** [AmazingAmpharos/OoT-Randomizer#127]
I'm running a randomized ROM on all dungeons required and I'm stuck on the water temple, the last one I still have to clear. I don't have the song of time (the only song i don't have) and in this seed it's located in its vanilla location (getting the 3 stones). I don't know if this is finishable without skips because after the fight with shadow link, and the "grappling upgrade" there is a block of time blocking the way.

Here is the seed 431134838
The parameters are
Rainbow bridge - All dungeons
All tunics and low health - Random
No spoiler log
Compress patched rom
Open forest and door of time
Place maps and compasses

**Comment by ThamanVelasquezBice** [comment]
I presume this also means you do not have Longshot? If you do, you can save and reboot the game and you can access the boss in this way

**Comment by BenoitGeslain** [comment]
You were right, I thought I didn't have the boss key my bad. Thanks for the help
