### ISSUE TITLE
Circular Dependency with forest items

### ISSUE THREAD

**Issue by CitrusRain** [AmazingAmpharos/OoT-Randomizer#128]
Need to get Saria's song to get the Forest Temple. 
![1 oot medallions-openforest-opendoor 198614392-comp 2018-09-12 00 21 28](https://user-images.githubusercontent.com/2942262/45402255-be246680-b622-11e8-9201-8bc02ca7f14d.png)
Need to get the Spiritual Stone of the Forest to get Saria's Song.
![1 oot medallions-openforest-opendoor 198614392-comp 2018-09-12 00 20 05](https://user-images.githubusercontent.com/2942262/45402253-be246680-b622-11e8-8465-6ff340a640fc.png)
Need to get to Forest Temple to get the Spiritual Stone of the Forest.
![1 oot medallions-openforest-opendoor 198614392-comp 2018-09-12 00 21 08](https://user-images.githubusercontent.com/2942262/45402254-be246680-b622-11e8-97bb-65922b9fc20d.png)

Filename generated by randomizer: OoT medallions-openforest-opendoor 198614392-comp

**Comment by flagrama** [comment]
Are you sure Minuet of Forest isn't available somewhere?

**Comment by CitrusRain** [comment]
What else would be song of the dancing gorons?

**Comment by CitrusRain** [comment]
Oh. Minuet... let me check

**Comment by flagrama** [comment]
Do you have a spoiler log I can look at? If not do you have the Seed and Settings so I can force generate one?

**Comment by CitrusRain** [comment]
I left the seed blank. Was hoping that was the number in the filename that I edited into the original post.
Did not generate a spoiler log.

**Comment by flagrama** [comment]
Did you leave Maps and Compasses on or off? And are hints on or off?

**Comment by CitrusRain** [comment]
Maps and compasses are on.
Image above is the rumble pack gossip stone hint thing.

**Comment by flagrama** [comment]
Lol, sorry for the dumb questions for seed and hints. I just ask them when I need them and forget to look and see if it was already mentioned.

So you are unable to finish Shadow Temple, Jabu Jabu's Belly, and Fire Temple? Those dungeons will give you the Forest/Fire/Water Medallions which will give you access to Nocturne spot Which will give you Minuet of Forest.

**Comment by CitrusRain** [comment]
Haven't found Din's fire to open shadow temple
Haven't found ruto's letter, so king zora blocks the way in both eras
-- can't afford to buy a blue fire because no wallet upgrades have been found
Currently in the fire temple with no goron tunic. Hearing the chanting that was removed from the game for the first time in my life and in awe about it.

**Comment by flagrama** [comment]
I don't think you have run into a logic error yet.

Here is your spoiler log: https://pastebin.com/gEfZpDds
I recommend generating one every time you generate a seed.
If you still can't manage a way through with this then come back here and explain where you got stuck.

**Comment by CitrusRain** [comment]
Thanks. TBH, I feel a bit silly coming in here forgetting about the warp song.
