### ISSUE TITLE
Problem to get the bow

### ISSUE THREAD

**Issue by FrenchMos** [AmazingAmpharos/OoT-Randomizer#13]
Hello,
While playing seed 795780070, the bow has to be taken from the Forest Temple Block Push Chest, which is activated by the bow itself if I'm right (I'm not really knowledgeable about the exact name of each chest). 
[OoT_medallions-opendoor_795780070_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2020786/OoT_medallions-opendoor_795780070_Spoiler.txt)

Thank you for your hard work
Heartily

**Comment by AmazingAmpharos** [comment]
That was a pure oversight in the logic; I completely forgot to set the rule for that chest. That seed is indeed impossible. Sorry that one didn't work out, but thanks for the report. I'm pushing a fix for that right away.
