### ISSUE TITLE
Program not responding

### ISSUE THREAD

**Issue by Sirlias** [AmazingAmpharos/OoT-Randomizer#134]
Every time I try to open ootrandamizer.exe instead of going to the page to select the randomization you want, it immediately says it is not responding and then cant find the issue. This was happening before when I tried to open retroarch but I updated my gpu drives and it fixed that but not the randomizer. I have uninstalled, redownloaded, and reinstalled several times to try and get it to work, to no avail. I am very new to this kind of thing and don't really know where to look for problems. Any help is appreciated. Thanks.

**Comment by flagrama** [comment]
You may find help easier with this kind of stuff on the discord server: https://discord.gg/GyRhrUj

**Comment by Sirlias** [comment]
Thank you. The three answers I got (for those who might have the same issue) where:

1) add the whole folder to your antivirus exceptions.
2) move the whole file from program files (x86) to the desktop.
3)use the source code http://bit.ly/NotWindows (<--this is the one that worked for me)
