### ISSUE TITLE
dev branch: MQ Compasses Show locations

### ISSUE THREAD

**Issue by akaps** [AmazingAmpharos/OoT-Randomizer#136]
Repro Steps:
1. Seed found: VQF5SW21LS-0 (with spoiler text, generated out of 5 seeds)
2. Get the Compass for a MQ Dungeon
     King Dodongo Heart has the Dodongo's Cavern MQ Compass. It's the one that was most obvious to me
3. Go to the entrance of Dodongo's Cavern

Expected:
Entrance has no chest in the west (This is the Map in normal mode)

Actual:
Compass shows a chest at that location

Notes:
I don't know anything about the ROM, so maybe map data can't be manipulated like this. Would be cool to support a corrected Compass.
Chests sort of track correctly. That is, collecting all the chests in a dungeon clears the chests from the map. Dodongo's Cavern was the only one that didn't seem to fully clear

**Comment by AmazingAmpharos** [comment]
This was something that was fixed fairly recently and one of the last things done to make MQ fully functional, compasses pointing to accurate information in MQ dungeons. It's still new and still might have issues (I think Jabu's B1 has odd behavior?), but we'll be monitoring it going forward.
