### ISSUE TITLE
error on gossip stone in dodongo cavern

### ISSUE THREAD

**Issue by jesse100190** [AmazingAmpharos/OoT-Randomizer#142]
![snap0000](https://user-images.githubusercontent.com/41838604/46029659-ac7a9e80-c0b9-11e8-9da4-bcc06282b2cb.jpg)
i ran into this error while exploring dodongo cavern in master quest

**Comment by AmazingAmpharos** [comment]
This is known and will be fixed shortly. Thank you for the report though!
