### ISSUE TITLE
I'm stuck?

### ISSUE THREAD

**Issue by Thanatos55** [AmazingAmpharos/OoT-Randomizer#144]
I am so close to finishing the entire game, I have every item except for the mirror shield which seems to be necessary to complete the Spirit Temple. I've used a tracker and have exhausted what seems like every option left.
My seed 930762065 and I did not create a spoiler file. I have fast Gannon, open Forest, open Door of Time, and I have compasses and enabled. I don't know what I'm missing

**Comment by AmazingAmpharos** [comment]
Assuming this is 2.0 and I guessed all settings correctly, it's in the left invisible chest in the hallway leading to the adult Iron Knuckle in Spirit Temple which is somewhat ironically very close to where Mirror Shield was in the original game. In the future, this sort of query is better served for the discord where more people can find and provide quick gameplay help.
