### ISSUE TITLE
Why are ice traps so bad?

### ISSUE THREAD

**Issue by Kongolan** [AmazingAmpharos/OoT-Randomizer#155]
Ice traps should be danger, like always setting you down to 1 heart and when you have 1 heart then it takes you to a quarter left, so you are in danger. I don't understand why to nerf them beside of the time loss being frozen.

**Comment by flagrama** [comment]
Ice traps just work the way they do in vanilla. AFAIK most of the devs don't really want to stray from vanilla mechanics. The only nerfing of the ice traps I know of is apparently they are disabled for OHKO mode as they cause a softlock.

**Comment by Kongolan** [comment]
Seems like a wrong reference on the pull request.

@flagrama Since when only 1 quarter of a heart is a default damage of icetraps? They were much stronger?

**Comment by Kongolan** [comment]
Ok, couldn't find anything about this on the wikis, so i thought it was changed.

I close this issue.
