### ISSUE TITLE
Randomizer didn't do what it suppose to do. 

### ISSUE THREAD

**Issue by TsynkZZZ** [AmazingAmpharos/OoT-Randomizer#158]
I set my settings, added a seed, waited on it to patch a ROM together and the end result was the unrandomized ROM. I'm at the point where I am frustrated. I even used the output ROM the randomizer created.

**Comment by flagrama** [comment]
What is the file name of the file you are trying to run? It should be something like `OoT_Medallions_123154-comp.z64`

**Comment by TsynkZZZ** [comment]
ZOOTDEC.z64

**Comment by flagrama** [comment]
That is the uncompressed non-randomized rom. If you used the installer the actual output rom should be in your Documents folder within a folder that the randomizer creates for you.

**Comment by TsynkZZZ** [comment]
Yeah, I now see where I didn't select proper.

**Comment by TsynkZZZ** [comment]
Thanks!
