### ISSUE TITLE
locked in fire temple?

### ISSUE THREAD

**Issue by Darkenedxr** [AmazingAmpharos/OoT-Randomizer#159]
OoT_dungeons-opendoor_387874636-comp.
Version 2.0
I dont have the spoiler log sorry

So im in the fire temple and i have all the items needed to complete the dungeon, the thing is, i only have 2 chests left to open and the boss to beat, i dont have the boss key and the chests i have left to open are locked behind a key door in the fire maze room, the hammer chest and the goron with the block of time on top of his cell.

My guess is that the boss key is in one of the chest, the boss has a normal key and the last chess has a key too.

The boss has the light medallion which i need for ganon tower
I'm at a loss here, i dont know if the seed is unbeatable or if i messed up something 

![oot_dungeons-opendoor_387874636-comp-181011-000435](https://user-images.githubusercontent.com/44047139/46780491-02228e00-cceb-11e8-9b25-f3fd9a64008d.png)
![oot_dungeons-opendoor_387874636-comp-181011-000452](https://user-images.githubusercontent.com/44047139/46780492-02bb2480-cceb-11e8-9e37-2f9245073983.png)

![oot_dungeons-opendoor_387874636-comp-181011-002425](https://user-images.githubusercontent.com/44047139/46780687-1c10a080-ccec-11e8-9631-4d36603d7a3d.png)
.i did not join the other floors screenshot since there is nothing left on them.

**Comment by flagrama** [comment]
If you have Hover Boots and Hammer you can skip that locked door by hovering to the platform you knock down for the boss room and hammering the rusted over switch. This will let you into the room with the Goron and the Song of Time block and should also let you continue on to the Hammer chest.

**Comment by Darkenedxr** [comment]
yeah that works, didnt think about it thanks a ton
