### ISSUE TITLE
Lens of truth is guaranteed if  normaly used, but is magic?

### ISSUE THREAD

**Issue by accept8605** [AmazingAmpharos/OoT-Randomizer#16]
Heres the spoiler log of this pretty complicated seed

https://pastebin.com/SH5NuC0u

Gerudo Training Grounds Hammer Room Switch Chest: Boomerang
Song from Ocarina of Time: Zeldas Lullaby
That means you have to get  Gerudo Training Grounds Hammer Room Switch Chest without magic.if you want ZL

is that possible without glitches and without doing the lens of truth path without magic?

**Comment by CMuncey** [comment]
I'm not sure why you need magic to get to GTG hammer room?

This should get you there, right?
Epona's from Saria
Get Epona
Cross the gap in Gerudo Valley
Get Gerudo Card
Enter GTG
Go to hammer room

**Comment by CMuncey** [comment]
Go right when you enter, kill the enemies in there, then jump across the lava room pillars (the spoiler says you should have hookshot at this point, so you can grab the torch at the end with that), and then you're in the hammer room.

**Comment by accept8605** [comment]
Ive never seen anyone do that room without longshot or hover boots I guess. I didnt manage to "jump across"

**Comment by accept8605** [comment]
Never mind, its easy with song of time. But some other thing: Navi seems to be broken for me with this seed. She keeps talking about Death Mountain though I have completed fire temple?
