### ISSUE TITLE
What is the output named???

### ISSUE THREAD

**Issue by turtleisaac1** [AmazingAmpharos/OoT-Randomizer#163]
So I tried randomizing a OoT ROM, and it told me it wasn’t the 1.0 version. No big deal, got myself the 1.0. Now I have randomized it and the output directory contains 3 files, all of them are .z64 file extensions. One is called ZOOTDEC.z64, and the other two are called OoT_medallions-openforest-opendoor_338646186-comp and OoT_medallions-openforest-opendoor_338646186. Which one of these is the correct rom to run in the emulator??

**Comment by CMuncey** [comment]
You'll want to use the one that ends in "-comp.z64". That's the compressed version of the rom. The one with the long name that doesn't have "-comp.z64" at the end is the uncompressed version, which is prone to crashing in emulators. ZOOTDEC.z64 is the uncompressed version of the vanilla rom. If you pass that to the randomiser the next time you run it, it won't have to decompress the vanilla rom again, which will save like a 10th of a second.. doesn't really help, but there's no real reason not to..

**Comment by AmazingAmpharos** [comment]
I think CMuncey's answer is pretty clear, and the output should be even simpler to understand in 3.0.
