### ISSUE TITLE
Broken Seed

### ISSUE THREAD

**Issue by JakePlanet** [AmazingAmpharos/OoT-Randomizer#167]
Running the parameters 
No spoiler log
Compress patched rom
Open door of time
Open forest
Place dungeon itemz
Only ensure seed is beatable
Seed 555
Ive collected every piece of heart opened every chest in every dungeon. Done all the side quests. 
Im missing the long shot and light arrows mainly. I have every medallion via glitching through points. I have absolutely no way to beat the game now.

**Comment by flagrama** [comment]
Hints enabled or disabled is also required as it does affect logic from time to time apparently. In this case they appear to be identical.

Here is your spoiler log: https://pastebin.com/fra9P15k

Looks like you play sun song in the readead grave in the graveyard for light arrows and your hookshots are spirit temple map chest and one of the chests in the gerudo training grounds maze. Both look to be logically possible for you.

**Comment by JakePlanet** [comment]
I cannot get through the gerudo maze. I cant beat the silver rupee room without the longshot and i cant get above in the spinning faces room. All of my keys have been used and cannot seem to get any further

**Comment by flagrama** [comment]
Hookshot is all you need for the silver rupee room. It's a bit precise but if you position yourself correctly you can grab the target by the door. It is in logic and intended to be so.

**Comment by JakePlanet** [comment]
Absolutely right. I feel ridiculous. Thank you so much for your help
