### ISSUE TITLE
Dev Branch: Can't use Pocket Cucco as child

### ISSUE THREAD

**Issue by Lum4r** [AmazingAmpharos/OoT-Randomizer#172]
I randomized the Weird Egg and found it in the Spirit Temple as an adult. I warped back to the Temple of Time and put the sword back. Then I went straight to the castle, where it hatched as normal, but the Pocket Cucco is grayed out for Child Link. I used a glitch to equip it anyway, but it still won't wake Talon up.

The weird thing is, it does let me equip it as an adult, but it's a little too late at that point.

**Comment by flagrama** [comment]
Pocket Egg is the adult trade item and hatches into Pocket Cucco. Weird Egg is the child item and hatches into an item called just Cucco.

**Comment by Lum4r** [comment]
Yep, my mistake

**Comment by phixtyseven** [comment]
Talon is very particular in how he starts his morning routine. You can't get him up for just any old cock.
