### ISSUE TITLE
Decompressor.exe returns "couldn't find table" error

### ISSUE THREAD

**Issue by Color-Printer** [AmazingAmpharos/OoT-Randomizer#18]
Cannot use the randomizer because the decompressor returns a very unhelpful "couldn't find table" error.

**Comment by CMuncey** [comment]
What version ROM are you using? The "couldn't find table" error happens if the decompressor can't find the internal file table that the n64 uses to determine what files are where in the ROM.

**Comment by Color-Printer** [comment]
Project64 claims it's a 1.0 version but I'm not so sure. It's a .n64 file

**Comment by CMuncey** [comment]
And it's the NTSC version? Not PAL, right?

**Comment by Color-Printer** [comment]
Yes, it is an NTSC 1.0 .n64 file, with a CRC-32 hash of EC95702D.

**Comment by CMuncey** [comment]
I'm not at home at the moment, but I'll use crc when I can to see if that matches

**Comment by krimtonz** [comment]
We found out that certain ROMs have a strange encoding to them, while they're fine in emulators the Decompressor doesn't know how to handle them. Cmuncey and I figured out how to fix that, Once the Updated Decompressor is added into the Repo you should have no problem using your ROM.

**Comment by AmazingAmpharos** [comment]
The decompressor has been updated with the 1.0 release to address this issue. Thank you for the report, but pending further problems, I believe this issue is solved.
