### ISSUE TITLE
Unplayable seed: Weird Egg issue?

### ISSUE THREAD

**Issue by JasonCastle** [AmazingAmpharos/OoT-Randomizer#182]
I found a seed which doesn't seem to be playing nice. I think there could be a conflict between the "Kakariko Closed" and "shuffle Weird Egg" settings not communicating? I'm not nearly enough of an expert to really play this without some guidance yet although every play through im getting better.  However after getting stuck in this seed I took a look at the spoiler and found there's no way I could progress.

Let's say I wanted to become an adult. I need the song of time, as the door is locked. The song of time is from King Dodongo's PoH.  You can't open the cavern without Zelda's letter, as I have Kakiriko Closed. Zelda's letter is in Zelda's letter location. So you need the Weird Egg to wake up Talon.  The Weird Egg is in the PoH in the wall of Death Mountain Crater. You need Zelda's letter to get to Death Mountain. Am I right?

Seed is:M1DN4B17CH
Settings:B22FFQAQCN5WAKBAJB

**Comment by flagrama** [comment]
You can get to Goron City from the Lost Woods with bombs or Din's Fire.

Could you post your spoiler log somewhere to take a closer look?

**Comment by JasonCastle** [comment]
Hmm, I'll try Din's fire next. I did get that from the dog lady.

**Comment by JasonCastle** [comment]
Thank you for your help, never thought of that
