### ISSUE TITLE
Spirit Temple Topmost Chest?

### ISSUE THREAD

**Issue by tommaniacal** [AmazingAmpharos/OoT-Randomizer#186]
Which chest is this referring to? I've already completed the spirit temple but I apparently haven't gotten this one yet.

**Comment by flagrama** [comment]
I can't say for sure, but I believe it may be the chest in the room with the two mirrors you turn to lower the platform so you can reach the boss door. There is a sun before the first mirror that you can use the mirror shield on when the mirror is in it's default position. It gives you a "Wrong" sound and drops a chest.

**Comment by theRealThomasDavidson** [comment]
is it unreachable?

**Comment by flagrama** [comment]
Just climb all the way back up there, turn the mirror back to its default position (if it doesn't just reset from leaving the temple in the first place) and then you should be able to activate it just fine.

**Comment by tommaniacal** [comment]
> I can't say for sure, but I believe it may be the chest in the room with the two mirrors you turn to lower the platform so you can reach the boss door. There is a sun before the first mirror that you can use the mirror shield on when the mirror is in it's default position. It gives you a "Wrong" sound and drops a chest.

This was it! Thank you!
