### ISSUE TITLE
gtg logic broken

### ISSUE THREAD

**Issue by abeccaro** [AmazingAmpharos/OoT-Randomizer#191]
I'm stuck at gtg because I need an item in one of the chests behind the heavy block but I can't reach that room without longshot or hover boots. Can I actually collect all the silver rupees in the left side without them or is the logic broken?

Reference spoiler: [OoT_MJ2MKZANBJFGBKRJAB_6ZLE2581NQ_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2590602/OoT_MJ2MKZANBJFGBKRJAB_6ZLE2581NQ_Spoiler.txt) (12: weird egg)

**Comment by Niamek** [comment]
You don't need longshot to reach taht target on the celling.

**Comment by Niamek** [comment]
Try harder. ;)

**Comment by abeccaro** [comment]
oh wow I feel so stupid. Thanks for the help
