### ISSUE TITLE
Possibly stuck?

### ISSUE THREAD

**Issue by nighthawk144** [AmazingAmpharos/OoT-Randomizer#193]
Almost at the end of the game and i see now that for my seed i get the progressive hookshot from the frog game. Issue is Sarias song which i belive i need for the frog game is from the forest trial at ganons castle which i cant get to until i finish everything else. I am just missing Koiri emerald, water medallion, and light medallion. Is there a trick i am missing?

[OoT_M43JKRANFJBAA3BJAB_DT53WX8VG4_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2593101/OoT_M43JKRANFJBAA3BJAB_DT53WX8VG4_Spoiler.txt)

**Comment by BashPrime** [comment]
You can complete the Fire and Spirit Temples without the Longshot, then dive into Ganon's Castle and get the Longshot from the Forest Trial.

**Comment by nighthawk144** [comment]
I feel dumb, i just found the boots in the spirit temple which ties everything together. thank!
