### ISSUE TITLE
Stuck because of a possible logic error?

### ISSUE THREAD

**Issue by Crabble42** [AmazingAmpharos/OoT-Randomizer#195]
[OoT_B44QB9JRQK7AAKAJJB_8R0BOQU5BY_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2593650/OoT_B44QB9JRQK7AAKAJJB_8R0BOQU5BY_Spoiler.txt)

I have a run that is seemingly unbeatable by normal means. The problem is as follows:
I need the Hammer to proceed in the Fire temple, since I did not get a small key in the Room with Darunia and cannot defeat Volvagia without it either.
I need to progress the Fire Temple to get the second strength upgrade, in order to enter the Spirit Temple as an adult and get Epona's song.
I need to win the Horseback archery game to gain the Hammer, which is not possible if I'm lacking Epona's song...

Correct me if I'm wrong, but I don't see how I am supposed to beat this run.

**Comment by flagrama** [comment]
That's a Gold Skulltula that has Hammer. You don't need Epona for that. You just need the Longshot to cross the broken bridge.

**Comment by phixtyseven** [comment]
Had me fooled too, I didn't notice the GS part

**Comment by Crabble42** [comment]
aaah! I see. thank you very much!
