### ISSUE TITLE
According to spoiler log, I should have 3 strength upgrades, but I only have the silver gauntlets

### ISSUE THREAD

**Issue by mishael515** [AmazingAmpharos/OoT-Randomizer#196]
The three strength upgrades in my spoiler log are:
Zora River Upper Freestanding PoH: Progressive Strength Upgrade
DMC Deku Scrub Bombs: Progressive Strength Upgrade
Gerudo Training Grounds Hammer Room Clear Chest: Progressive Strength Upgrade

I have both Zora's river heart pieces, Death Mountain Crater's scrub grotto has been cleared, and GTG's hammer room's chests are both empty.  Not sure why I still only have the silver gauntlets.  The game is near cleared otherwise.

[OoT_RL2RKKTPF2NJAKAJAB_EJ47U3NCR5-2_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2602552/OoT_RL2RKKTPF2NJAKAJAB_EJ47U3NCR5-2_Spoiler.txt)

**Comment by flagrama** [comment]
The DMC scrub is the one that appears near the ladder only as a child. Are you sure you got that one?

**Comment by mishael515** [comment]
Thanks, I did forget that one.
