### ISSUE TITLE
99 Skulltulas

### ISSUE THREAD

**Issue by NicolinasSurel** [AmazingAmpharos/OoT-Randomizer#198]
Hello! According to the World Map and the Dungeon Maps, I've collected all the Gold Skulltula tokens, yet the game says I only have 99. 
Sorry if this has already been addressed before, but I'd really like to 100% my file. I've attached my spoiler log.

[OoT_R92R37BNYNH6AKAJ7B_Y7FSKJEA5Q_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2622328/OoT_R92R37BNYNH6AKAJ7B_Y7FSKJEA5Q_Spoiler.txt)

Thanks!

**Comment by flagrama** [comment]
It might be that the Maps only track Vanilla Token locations. So you've gotten all the Vanilla Tokens and your 100th token is in one of the other checks in the game.

Edit: Have you gotten the one from picking up the "Ocarina of Time" in the moat after getting all 3 Stones?

**Comment by NicolinasSurel** [comment]
I appreciate the quick feedback! I've collected all the chests according to the dungeon map compasses. I grabbed the Ocarina of Time skulltula. 

Edit: I found it! I had yet to walk into Kakariko from the front entrance after collecting the Forest, Fire, and Water medallions. Thank you for the extra set of eyes!
