### ISSUE TITLE
Unbeatable seed?

### ISSUE THREAD

**Issue by mgill5** [AmazingAmpharos/OoT-Randomizer#199]
My spoiler log is below - I **think** step 8 might be a bug, because the following room is not reachable without first getting the longshot.

  Shadow Temple Spike Walls Left Chest: Progressive Hookshot

This is the room I'm stuck at - you can't reach the door on the top of the platform without the longshot (**as far as I know - please let me know if there is another method I'm missing**):
https://www.zeldadungeon.net/Zelda05/Walkthrough/12/12_Shadow44_Large.jpg

I have confirmed (using levitate cheat) that **the longshot was after this room** (it was in the boss key room, in the small chest), potentially making this an unbeatable seed.

OoT Randomizer Version v3.0  -  Seed: ZMACHFLXI0

Settings (DL23ARANFA2AAKAJAB):
create_spoiler:                            True
open_forest:                               True
open_kakariko:                             False
open_door_of_time:                         False
gerudo_fortress:                           normal
bridge:                                    medallions
all_reachable:                             True
bombchus_in_logic:                         False
one_item_per_dungeon:                      False
trials_random:                             False
trials:                                    6
no_escape_sequence:                        True
no_guard_stealth:                          False
no_epona_race:                             False
fast_chests:                               True
big_poe_count_random:                      True
big_poe_count:                             1
free_scarecrow:                            False
shuffle_kokiri_sword:                      True
shuffle_weird_egg:                         True
shuffle_ocarinas:                          True
shuffle_song_items:                        True
shuffle_gerudo_card:                       False
shuffle_scrubs:                            off
shopsanity:                                off
shuffle_mapcompass:                        dungeon
shuffle_smallkeys:                         dungeon
shuffle_bosskeys:                          dungeon
enhance_map_compass:                       True
unlocked_ganondorf:                        False
tokensanity:                               off
quest:                                     vanilla
logic_skulltulas:                          0
logic_no_night_tokens_without_suns_song:   False
logic_no_big_poes:                         False
logic_no_child_fishing:                    True
logic_no_adult_fishing:                    True
logic_no_trade_skull_mask:                 False
logic_no_trade_mask_of_truth:              False
logic_no_1500_archery:                     False
logic_no_memory_game:                      False
logic_no_second_dampe_race:                False
logic_no_trade_biggoron:                   False
logic_earliest_adult_trade:                pocket_egg
logic_latest_adult_trade:                  claim_check
logic_tricks:                              False
logic_man_on_roof:                         False
logic_child_deadhand:                      False
logic_dc_jump:                             False
logic_windmill_poh:                        False
logic_crater_bean_poh_with_hovers:         False
logic_zora_with_cucco:                     False
logic_zora_with_hovers:                    False
logic_fewer_tunic_requirements:            False
logic_morpha_with_scale:                   True
logic_lens:                                all
ocarina_songs:                             False
correct_chest_sizes:                       False
clearer_hints:                             False
hints:                                     agony
text_shuffle:                              none
difficulty:                                normal

Locations:

Links Pocket: Light Medallion
Queen Gohma: Kokiri Emerald
King Dodongo: Water Medallion
Barinade: Zora Sapphire
Phantom Ganon: Goron Ruby
Volvagia: Forest Medallion
Morpha: Spirit Medallion
Twinrova: Shadow Medallion
Bongo Bongo: Fire Medallion
Song from Saria: Slingshot
Song from Ocarina of Time: Recovery Heart
Sheik at Colossus: Piece of Heart
Sheik at Temple: Stone of Agony
Impa at Castle: Bolero of Fire
Sheik in Kakariko: Bow
Song at Windmill: Progressive Wallet
Song from Composer Grave: Piece of Heart
Sheik in Crater: Recovery Heart
Song from Malon: Rupees (20)
Sheik Forest Song: Piece of Heart
Sheik in Ice Cavern: Map (Ice Cavern)
Kokiri Sword Chest: Hylian Shield
Mido Chest Top Left: Progressive Strength Upgrade
Mido Chest Top Right: Bombs (20)
Mido Chest Bottom Left: Ocarina
Mido Chest Bottom Right: Song of Time
Skull Kid: Lens of Truth
Ocarina Memory Game: Progressive Hookshot
Target in Woods: Piece of Heart
LW Deku Scrub Deku Stick Upgrade: Light Arrows
Gift from Saria: Sarias Song
Ocarina of Time: Bomb Bag
Underwater Bottle: Bombs (5)
Lake Hylia Sun: Rupees (5)
Lake Hylia Freestanding PoH: Recovery Heart
Diving in the Lab: Arrows (30)
Child Fishing: Deku Shield
Adult Fishing: Rupees (20)
Gerudo Valley Waterfall Freestanding PoH: Arrows (30)
Gerudo Valley Crate Freestanding PoH: Recovery Heart
Gerudo Valley Hammer Rocks Chest: Piece of Heart (Treasure Chest Game)
Gerudo Fortress Rooftop Chest: Piece of Heart
Horseback Archery 1000 Points: Bombs (10)
Horseback Archery 1500 Points: Heart Container
Haunted Wasteland Structure Chest: Deku Stick Capacity
Colossus Freestanding PoH: Rupees (5)
Desert Colossus Fairy Reward: Rupees (5)
Zelda: Slingshot
Malon Egg: Bomb Bag
Hyrule Castle Fairy Reward: Rupees (5)
Ganons Castle Fairy Reward: Piece of Heart
10 Big Poes: Hylian Shield
Child Shooting Gallery: Suns Song
Bombchu Bowling Bomb Bag: Serenade of Water
Bombchu Bowling Piece of Heart: Piece of Heart
Treasure Chest Game: Arrows (10)
Dog Lady: Goron Tunic
Man on Roof: Piece of Heart
Anju as Adult: Arrows (10)
Anjus Chickens: Heart Container
10 Gold Skulltula Reward: Piece of Heart
20 Gold Skulltula Reward: Piece of Heart
30 Gold Skulltula Reward: Piece of Heart
40 Gold Skulltula Reward: Piece of Heart
50 Gold Skulltula Reward: Piece of Heart
Impa House Freestanding PoH: Arrows (30)
Windmill Freestanding PoH: Piece of Heart
Adult Shooting Gallery: Rupees (5)
Graveyard Freestanding PoH: Rupees (50)
Gravedigging Tour: Recovery Heart
Shield Grave Chest: Piece of Heart
Heart Piece Grave Chest: Nocturne of Shadow
Composer Grave Chest: Arrows (10)
Hookshot Chest: Prelude of Light
Dampe Race Freestanding PoH: Nayrus Love
Death Mountain Bombable Chest: Piece of Heart
DM Trail Freestanding PoH: Rupee (1)
Goron City Leftmost Maze Chest: Bottle with Poe
Goron City Left Maze Chest: Bombs (5)
Goron City Right Maze Chest: Rupees (50)
Goron City Pot Freestanding PoH: Heart Container
Rolling Goron as Child: Arrows (30)
Link the Goron: Magic Meter
Darunias Joy: Arrows (30)
DM Crater Wall Freestanding PoH: Slingshot
Biggoron: Rupees (50)
DM Crater Volcano Freestanding PoH: Rupees (20)
Crater Fairy Reward: Rupees (5)
Mountain Summit Fairy Reward: Deku Nuts (10)
Frog Ocarina Game: Progressive Strength Upgrade
Frogs in the Rain: Piece of Heart
Zora River Lower Freestanding PoH: Eponas Song
Zora River Upper Freestanding PoH: Zeldas Lullaby
Diving Minigame: Piece of Heart
Zoras Domain Torch Run: Progressive Wallet
King Zora Thawed: Deku Nut Capacity
Zoras Fountain Iceberg Freestanding PoH: Rupees (50)
Zoras Fountain Bottom Freestanding PoH: Bombchus (10)
Zoras Fountain Fairy Reward: Bottle
Talons Chickens: Mirror Shield
Lon Lon Tower Freestanding PoH: Piece of Heart
Ganons Tower Boss Key Chest: Ice Trap
Kokiri Forest Storms Grotto Chest: Rupees (200)
Lost Woods Generic Grotto Chest: Piece of Heart
Deku Theater Skull Mask: Piece of Heart
Deku Theater Mask of Truth: Arrows (10)
LW Grotto Deku Scrub Deku Nut Upgrade: Piece of Heart
Wolfos Grotto Chest: Rupees (5)
Remote Southern Grotto Chest: Ice Trap
Field Near Lake Outside Fence Grotto Chest: Deku Shield
HF Grotto Deku Scrub Piece of Heart: Rupees (5)
Field West Castle Town Grotto Chest: Piece of Heart
Tektite Grotto Freestanding PoH: Arrows (5)
Redead Grotto Chest: Heart Container
Kakariko Back Grotto Chest: Recovery Heart
Mountain Storms Grotto Chest: Rupees (5)
Top of Crater Grotto Chest: Ice Trap
Zora River Plateau Open Grotto Chest: Requiem of Spirit
Deku Tree Lobby Chest: Bow
Deku Tree Compass Chest: Minuet of Forest
Deku Tree Compass Room Side Chest: Map (Deku Tree)
Deku Tree Basement Chest: Rupees (50)
Deku Tree Slingshot Chest: Rupees (50)
Deku Tree Slingshot Room Side Chest: Compass (Deku Tree)
Queen Gohma Heart: Rupees (5)
Dodongos Cavern Map Chest: Recovery Heart
Dodongos Cavern Compass Chest: Bow
Dodongos Cavern Bomb Flower Platform: Rupees (200)
Dodongos Cavern Bomb Bag Chest: Map (Dodongos Cavern)
Dodongos Cavern End of Bridge Chest: Heart Container
Chest Above King Dodongo: Compass (Dodongos Cavern)
King Dodongo Heart: Rupees (5)
Boomerang Chest: Compass (Jabu Jabus Belly)
Jabu Jabus Belly Map Chest: Song of Storms
Jabu Jabus Belly Compass Chest: Rupees (5)
Barinade Heart: Map (Jabu Jabus Belly)
Forest Temple First Chest: Small Key (Forest Temple)
Forest Temple Chest Behind Lobby: Boss Key (Forest Temple)
Forest Temple Well Chest: Small Key (Forest Temple)
Forest Temple Map Chest: Small Key (Forest Temple)
Forest Temple Outside Hookshot Chest: Small Key (Forest Temple)
Forest Temple Falling Room Chest: Piece of Heart
Forest Temple Block Push Chest: Dins Fire
Forest Temple Boss Key Chest: Rupees (200)
Forest Temple Floormaster Chest: Bottle with Green Potion
Forest Temple Bow Chest: Small Key (Forest Temple)
Forest Temple Red Poe Chest: Rupees (50)
Forest Temple Blue Poe Chest: Piece of Heart
Forest Temple Near Boss Chest: Map (Forest Temple)
Phantom Ganon Heart: Compass (Forest Temple)
Fire Temple Chest Near Boss: Small Key (Fire Temple)
Fire Temple Fire Dancer Chest: Small Key (Fire Temple)
Fire Temple Boss Key Chest: Ice Trap
Fire Temple Big Lava Room Bombable Chest: Rupees (5)
Fire Temple Big Lava Room Open Chest: Small Key (Fire Temple)
Volvagia Heart: Piece of Heart
Fire Temple Boulder Maze Lower Chest: Small Key (Fire Temple)
Fire Temple Boulder Maze Upper Chest: Boss Key (Fire Temple)
Fire Temple Boulder Maze Side Room: Small Key (Fire Temple)
Fire Temple Boulder Maze Bombable Pit: Small Key (Fire Temple)
Fire Temple Scarecrow Chest: Small Key (Fire Temple)
Fire Temple Map Chest: Piece of Heart
Fire Temple Compass Chest: Compass (Fire Temple)
Fire Temple Highest Goron Chest: Small Key (Fire Temple)
Fire Temple Megaton Hammer Chest: Map (Fire Temple)
Water Temple Map Chest: Small Key (Water Temple)
Water Temple Compass Chest: Deku Nut Capacity
Water Temple Torches Chest: Map (Water Temple)
Water Temple Dragon Chest: Small Key (Water Temple)
Water Temple Central Bow Target Chest: Small Key (Water Temple)
Water Temple Boss Key Chest: Small Key (Water Temple)
Morpha Heart: Small Key (Water Temple)
Water Temple Central Pillar Chest: Small Key (Water Temple)
Water Temple Cracked Wall Chest: Boss Key (Water Temple)
Water Temple Dark Link Chest: Compass (Water Temple)
Water Temple River Chest: Bombs (10)
Spirit Temple Child Left Chest: Small Key (Spirit Temple)
Spirit Temple Child Right Chest: Progressive Scale
Spirit Temple Child Climb East Chest: Small Key (Spirit Temple)
Spirit Temple Child Climb North Chest: Small Key (Spirit Temple)
Spirit Temple Compass Chest: Heart Container
Spirit Temple Early Adult Right Chest: Iron Boots
Spirit Temple First Mirror Right Chest: Boss Key (Spirit Temple)
Spirit Temple First Mirror Left Chest: Biggoron Sword
Spirit Temple Map Chest: Eyedrops
Spirit Temple Sun Block Room Chest: Small Key (Spirit Temple)
Spirit Temple Statue Hand Chest: Small Key (Spirit Temple)
Spirit Temple NE Main Room Chest: Deku Nuts (5)
Silver Gauntlets Chest: Bottle with Letter
Mirror Shield Chest: Ocarina
Spirit Temple Near Four Armos Chest: Rupees (20)
Spirit Temple Hallway Left Invisible Chest: Recovery Heart
Spirit Temple Hallway Right Invisible Chest: Ice Trap
Spirit Temple Boss Key Chest: Arrows (10)
Spirit Temple Topmost Chest: Compass (Spirit Temple)
Twinrova Heart: Map (Spirit Temple)
Shadow Temple Map Chest: Small Key (Shadow Temple)
Shadow Temple Hover Boots Chest: Small Key (Shadow Temple)
Shadow Temple Compass Chest: Small Key (Shadow Temple)
Shadow Temple Early Silver Rupee Chest: Small Key (Shadow Temple)
Shadow Temple Invisible Blades Visible Chest: Compass (Shadow Temple)
Shadow Temple Invisible Blades Invisible Chest: Recovery Heart
Shadow Temple Falling Spikes Lower Chest: Rupees (200)
Shadow Temple Falling Spikes Upper Chest: Small Key (Shadow Temple)
Shadow Temple Falling Spikes Switch Chest: Boss Key (Shadow Temple)
Shadow Temple Invisible Spikes Chest: Recovery Heart
Shadow Temple Freestanding Key: Rupees (5)
Shadow Temple Wind Hint Chest: Bombchus (5)
Shadow Temple After Wind Enemy Chest: Zora Tunic
Shadow Temple After Wind Hidden Chest: Hammer
Shadow Temple Spike Walls Left Chest: Progressive Hookshot
Shadow Temple Boss Key Chest: Deku Shield
Shadow Temple Hidden Floormaster Chest: Map (Shadow Temple)
Bongo Bongo Heart: Arrows (10)
Bottom of the Well Front Left Hidden Wall: Small Key (Bottom of the Well)
Bottom of the Well Front Center Bombable: Progressive Scale
Bottom of the Well Right Bottom Hidden Wall: Bombchus (10)
Bottom of the Well Center Large Chest: Farores Wind
Bottom of the Well Center Small Chest: Compass (Bottom of the Well)
Bottom of the Well Back Left Bombable: Small Key (Bottom of the Well)
Bottom of the Well Freestanding Key: Small Key (Bottom of the Well)
Bottom of the Well Defeat Boss: Rupees (20)
Bottom of the Well Invisible Chest: Map (Bottom of the Well)
Bottom of the Well Underwater Front Chest: Heart Container
Bottom of the Well Underwater Left Chest: Piece of Heart
Bottom of the Well Basement Chest: Ice Trap
Bottom of the Well Locked Pits: Piece of Heart
Bottom of the Well Behind Right Grate: Arrows (30)
Ice Cavern Map Chest: Magic Meter
Ice Cavern Compass Chest: Double Defense
Ice Cavern Iron Boots Chest: Compass (Ice Cavern)
Ice Cavern Freestanding PoH: Deku Stick Capacity
Gerudo Training Grounds Lobby Left Chest: Small Key (Gerudo Training Grounds)
Gerudo Training Grounds Lobby Right Chest: Bombchus (10)
Gerudo Training Grounds Stalfos Chest: Small Key (Gerudo Training Grounds)
Gerudo Training Grounds Beamos Chest: Piece of Heart
Gerudo Training Grounds Hidden Ceiling Chest: Rupees (20)
Gerudo Training Grounds Maze Path First Chest: Small Key (Gerudo Training Grounds)
Gerudo Training Grounds Maze Path Second Chest: Boomerang
Gerudo Training Grounds Maze Path Third Chest: Recovery Heart
Gerudo Training Grounds Maze Path Final Chest: Rupees (5)
Gerudo Training Grounds Maze Right Central Chest: Hover Boots
Gerudo Training Grounds Maze Right Side Chest: Piece of Heart
Gerudo Training Grounds Freestanding Key: Small Key (Gerudo Training Grounds)
Gerudo Training Grounds Underwater Silver Rupee Chest: Small Key (Gerudo Training Grounds)
Gerudo Training Grounds Hammer Room Clear Chest: Small Key (Gerudo Training Grounds)
Gerudo Training Grounds Hammer Room Switch Chest: Small Key (Gerudo Training Grounds)
Gerudo Training Grounds Eye Statue Chest: Weird Egg
Gerudo Training Grounds Near Scarecrow Chest: Small Key (Gerudo Training Grounds)
Gerudo Training Grounds Before Heavy Block Chest: Rupees (200)
Gerudo Training Grounds Heavy Block First Chest: Bomb Bag
Gerudo Training Grounds Heavy Block Second Chest: Small Key (Gerudo Training Grounds)
Gerudo Training Grounds Heavy Block Third Chest: Fire Arrows
Gerudo Training Grounds Heavy Block Fourth Chest: Deku Shield
Ganons Castle Forest Trial Chest: Piece of Heart
Ganons Castle Water Trial Left Chest: Progressive Strength Upgrade
Ganons Castle Water Trial Right Chest: Piece of Heart
Ganons Castle Shadow Trial First Chest: Piece of Heart
Ganons Castle Shadow Trial Second Chest: Heart Container
Ganons Castle Spirit Trial First Chest: Bombchus (20)
Ganons Castle Spirit Trial Second Chest: Small Key (Ganons Castle)
Ganons Castle Light Trial First Left Chest: Kokiri Sword
Ganons Castle Light Trial Second Left Chest: Boss Key (Ganons Castle)
Ganons Castle Light Trial Third Left Chest: Ice Arrows
Ganons Castle Light Trial First Right Chest: Bombs (20)
Ganons Castle Light Trial Second Right Chest: Small Key (Ganons Castle)
Ganons Castle Light Trial Third Right Chest: Rupees (5)
Ganons Castle Light Trail Invisible Enemies Chest: Rupees (200)
Ganons Castle Light Trial Lullaby Chest: Piece of Heart

Playthrough:

1: {
  Links Pocket: Light Medallion
  Mido Chest Top Left: Progressive Strength Upgrade
  Mido Chest Bottom Left: Ocarina
  Mido Chest Bottom Right: Song of Time
  Kokiri Shop Item 4: Buy Deku Stick (1)
  Gift from Saria: Sarias Song
  Malon Egg: Bomb Bag
  Child Shooting Gallery: Suns Song
  Dog Lady: Goron Tunic
  Deku Tree Lobby Chest: Bow
}
2: {
  Skull Kid: Lens of Truth
  Ocarina Memory Game: Progressive Hookshot
  LW Deku Scrub Deku Stick Upgrade: Light Arrows
  Master Sword Pedestal: Master Sword
  Heart Piece Grave Chest: Nocturne of Shadow
  Zora River Lower Freestanding PoH: Eponas Song
  Zora River Upper Freestanding PoH: Zeldas Lullaby
  Zora River Plateau Open Grotto Chest: Requiem of Spirit
}
3: {
  Song at Windmill: Progressive Wallet
  Link the Goron: Magic Meter
  Zoras Domain Torch Run: Progressive Wallet
  Epona: Epona
  King Dodongo: Water Medallion
  Forest Temple First Chest: Small Key (Forest Temple)
  Fire Temple Chest Near Boss: Small Key (Fire Temple)
}
4: {
  Gerudo Fortress North F1 Carpenter: Small Key (Gerudo Fortress)
  Gerudo Fortress North F2 Carpenter: Small Key (Gerudo Fortress)
  Gerudo Fortress South F1 Carpenter: Small Key (Gerudo Fortress)
  Gerudo Fortress South F2 Carpenter: Small Key (Gerudo Fortress)
  Forest Temple Block Push Chest: Dins Fire
  Fire Temple Big Lava Room Open Chest: Small Key (Fire Temple)
}
5: {
  Gerudo Fortress Carpenter Rescue: Carpenter Rescue
  Gerudo Fortress Membership Card: Gerudo Membership Card
  Shadow Temple Map Chest: Small Key (Shadow Temple)
  Shadow Temple Hover Boots Chest: Small Key (Shadow Temple)
}
6: {
  Gerudo Training Grounds Lobby Left Chest: Small Key (Gerudo Training Grounds)
  Gerudo Training Grounds Stalfos Chest: Small Key (Gerudo Training Grounds)
  Gerudo Training Grounds Maze Right Central Chest: Hover Boots
  Gerudo Training Grounds Freestanding Key: Small Key (Gerudo Training Grounds)
  Gerudo Training Grounds Hammer Room Clear Chest: Small Key (Gerudo Training Grounds)
  Gerudo Training Grounds Eye Statue Chest: Weird Egg
  Gerudo Training Grounds Near Scarecrow Chest: Small Key (Gerudo Training Grounds)
}
7: {
  Forest Temple Floormaster Chest: Bottle with Green Potion
  Zeldas Letter: Zeldas Letter
  Shadow Temple Compass Chest: Small Key (Shadow Temple)
  Shadow Temple Early Silver Rupee Chest: Small Key (Shadow Temple)
  Shadow Temple Falling Spikes Upper Chest: Small Key (Shadow Temple)
  Shadow Temple Falling Spikes Switch Chest: Boss Key (Shadow Temple)
  Gerudo Training Grounds Maze Path First Chest: Small Key (Gerudo Training Grounds)
}
8: {
  Talons Chickens: Mirror Shield
  Shadow Temple After Wind Hidden Chest: Hammer
  Shadow Temple Spike Walls Left Chest: Progressive Hookshot
  Bongo Bongo: Fire Medallion
  Gerudo Training Grounds Maze Path Second Chest: Boomerang
}
9: {
  Spirit Temple Child Left Chest: Small Key (Spirit Temple)
  Fire Temple Fire Dancer Chest: Small Key (Fire Temple)
}
10: {
  Spirit Temple Child Climb East Chest: Small Key (Spirit Temple)
  Spirit Temple Child Climb North Chest: Small Key (Spirit Temple)
  Spirit Temple Sun Block Room Chest: Small Key (Spirit Temple)
  Fire Temple Boulder Maze Lower Chest: Small Key (Fire Temple)
  Fire Temple Boulder Maze Side Room: Small Key (Fire Temple)
}
11: {
  Silver Gauntlets Chest: Bottle with Letter
  Fire Temple Boulder Maze Upper Chest: Boss Key (Fire Temple)
}
12: {
  Zora Shop Item 1: Buy Zora Tunic
  Jabu Jabus Belly Map Chest: Song of Storms
  Volvagia: Forest Medallion
}
13: {
  Frog Ocarina Game: Progressive Strength Upgrade
}
14: {
  Spirit Temple Early Adult Right Chest: Iron Boots
  Spirit Temple First Mirror Right Chest: Boss Key (Spirit Temple)
  Spirit Temple Statue Hand Chest: Small Key (Spirit Temple)
}
15: {
  Water Temple Cracked Wall Chest: Boss Key (Water Temple)
  Twinrova: Shadow Medallion
}
16: {
  Morpha: Spirit Medallion
}
17: {
  Ganons Castle Forest Trial Clear: Forest Trial Clear
  Ganons Castle Water Trial Left Chest: Progressive Strength Upgrade
  Ganons Castle Water Trial Clear: Water Trial Clear
  Ganons Castle Shadow Trial Clear: Shadow Trial Clear
  Ganons Castle Spirit Trial Second Chest: Small Key (Ganons Castle)
  Ganons Castle Spirit Trial Clear: Spirit Trial Clear
}
18: {
  Ganons Castle Fire Trial Clear: Fire Trial Clear
  Ganons Castle Light Trial Second Left Chest: Boss Key (Ganons Castle)
  Ganons Castle Light Trial Second Right Chest: Small Key (Ganons Castle)
}
19: {
  Ganons Castle Light Trial Clear: Light Trial Clear
}
20: {
  Ganon: Triforce
}

Way of the Hero:

Mido Chest Top Left: Progressive Strength Upgrade
Mido Chest Bottom Left: Ocarina
Mido Chest Bottom Right: Song of Time
Gift from Saria: Sarias Song
Malon Egg: Bomb Bag
Child Shooting Gallery: Suns Song
Skull Kid: Lens of Truth
Ocarina Memory Game: Progressive Hookshot
LW Deku Scrub Deku Stick Upgrade: Light Arrows
Heart Piece Grave Chest: Nocturne of Shadow
Zora River Lower Freestanding PoH: Eponas Song
Zora River Upper Freestanding PoH: Zeldas Lullaby
Zora River Plateau Open Grotto Chest: Requiem of Spirit
Link the Goron: Magic Meter
Forest Temple Block Push Chest: Dins Fire
Gerudo Training Grounds Maze Right Central Chest: Hover Boots
Gerudo Training Grounds Eye Statue Chest: Weird Egg
Talons Chickens: Mirror Shield
Shadow Temple After Wind Hidden Chest: Hammer
Shadow Temple Spike Walls Left Chest: Progressive Hookshot
Gerudo Training Grounds Maze Path Second Chest: Boomerang
Silver Gauntlets Chest: Bottle with Letter
Jabu Jabus Belly Map Chest: Song of Storms
Frog Ocarina Game: Progressive Strength Upgrade
Spirit Temple Early Adult Right Chest: Iron Boots
Ganons Castle Water Trial Left Chest: Progressive Strength Upgrade

Gossip Stone Hints:

They say that DKokiri Forest@ is on the&way of the hero.
They say that the DMarket@ is on the&way of the hero.
They say that DZora's River@ is on the&way of the hero.
They say that DDesert Colossus@ is on&the way of the hero.
They say that They say the Btreasure&thrown by Princess Zelda@ is a Ablast&bag@.
They say that Bghost hunters@ will be&rewarded with ALike Like's metal&meal@.
They say that the BMask of Truth@&yields some Asharp shafts@.
They say that the BOcarina of Time@&teaches a ABand-Aid@.
They say that BBiggoron@ crafts Awealth@.
They say that under the Bicy waters@&lies some Awall crawlers@.
They say that the Bfrozen cavern@&echoes with a Adungeon atlas@.
They say that a Bravaged village@&mourns with an Aarchery enabler@.
They say that the Bmusical amphibians@&have found the Aheavy lifty@.
They say that riding a Bbeanstalk in&the desert@ leads to a Acommon coin@.
They say that the Bcrater's melody@ is&a Afree heal@.
They say that a Bfrozen maze@ hoards&Amystic training@.
They say that a Bdeep forest@ hoards a&Agreen liquid@.
They say that a Bvast lake@ hoards&some Aexplosives@.
They say that a Apurple gem@ can be&found at BGoron City@.
They say that a Alittle love@ can be&found at Boutside Ganon's Castle@.
They say that a Ablue gem@ can be&found at BSacred Forest Meadow@.
They say that the Bgoddess of the&sand@ hoards Aclank cleats@.
They say that the Btest of thieves@&hoards a Achicken dilemma@.
They say that an Bimmense cavern@&hoards an Aarchery enabler@.
They say that a Acall for help@ can be&found at BDesert Colossus@.
They say that a Aportable bank@ can be&found at BZora's Domain@.
Medigoron sells the earliest Breath of&the Wild demo.
I heard @ isn't very good&at Zelda.
Mweep.^Mweep.^Mweep.^Mweep.^Mweep.^Mweep.^Mweep.^Mweep.^Mweep.^Mweep.^Mweep.^Mweep.
When all else fails, use Fire.
Ganondorf 2020!
They say that Bongo Bongo really&hates the cold.

**Comment by flagrama** [comment]
Backflip onto the chest. Read the Quirks to Know in the README.

**Comment by mgill5** [comment]
You're right - my mistake. Thanks for the quick reply.

**Comment by flagrama** [comment]
No problem. Have fun!
