### ISSUE TITLE
[ WinError 2] 

### ISSUE THREAD

**Issue by 1800safeauto** [AmazingAmpharos/OoT-Randomizer#201]
i am trying to use the Oot Randomizer v3.0 and the ROM i'm using is found at this site: not included due to issues with such site and the Dir is a random file i made so i can keep it in one place but nit is constantly giving me "[ WinError 2] the system cannot find the file specified" i looked up how to set up Oot randomizer v3.0 on youtube and followed the directions but still got the error i'm honestly confused and lost on how i messed up and hoping somebody can help me the link to the ROM can be found at this discord link: https://discordapp.com/channels/274180765816848384/438699704080007200 i am new at this whole thing so i hope you can help me and thank you for your time

**Comment by BashPrime** [comment]
I highly suggest removing that first link from your post, as distributing roms/rom links is illegal.

**Comment by flagrama** [comment]
Remove the link to the romsite in your issue. It is illegal to distribute copyrighted content.

Here is our normal troubleshooting steps in the Discord for dealing with WinError2:

> If you are experiencing the WinError2 problem - make sure of the following: 
>- Extract all files from the 3.0 release zip (All of which are: OoTRandomizer.exe, compress.exe & decompress.exe) 
>- Add the Randomizer folder to your antivirus exceptions/exclusions (Not sure how? google is your best friend) 
>- Alternatively, you could add all 3 files individually to your antivirus exceptions/exclusions 
>- The folder & programs possess read/write permissions 
>- Don't have it in Program files 
>- Be sure to Select Rom 
>- Make sure your unzip your US 1.0 Base rom 
>- Do NOT try to run the Randomizer via a desktop shortcut. Run it from within it's folder!!

**Comment by 1800safeauto** [comment]
thank you that worked
