### ISSUE TITLE
Stuck in Fire Temple

### ISSUE THREAD

**Issue by technodudegh** [AmazingAmpharos/OoT-Randomizer#203]
I've gone through the fire temple up to the room with the fire maze. I've gotten every chest up to this point (2 left plus boss) but im stuck without a key. And no, I don't have the boss key so i can't get to that. I've seen others with this issue but it was closed without resolution. Thanks for any help!

Here's the spoiler log
[OoT_R42JC9ANBACWAKAJAA_P76OOPV49P_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2658914/OoT_R42JC9ANBACWAKAJAA_P76OOPV49P_Spoiler.txt)

**Comment by flagrama** [comment]
In the fire maze you can Hover Boots to the platform you normally knock down to make a platform to Volvagia in vanilla. From there hammer the rusted switch and go through the door that opens. You've just bypassed the key door.

**Comment by technodudegh** [comment]
AHHH, you’re totally right. Thank you.
