### ISSUE TITLE
ocarina will not play songs unless it is a required area

### ISSUE THREAD

**Issue by Bradon-Lodwick** [AmazingAmpharos/OoT-Randomizer#204]
I am unable to use any songs on the ocarina.  This includes teleportation songs, sun song, etc.  If I am in an area that requires it and prompts the player with the bar (for example, a fairy fountain for zelda's lullaby) the game allows it, but nowhere else.

**Comment by rlbond86** [comment]
What emulator are you using?

**Comment by Bradon-Lodwick** [comment]
Bizhawk and emuhawk, I don't know if it is a problem with the emulator or the rom

**Comment by flagrama** [comment]
Make sure you're not holding L or the button bound to L as that will make any song you play not work. Also make sure the control stick isn't seen as being tilted at all as that will make it sound different and cause it not to work. Basically make sure only the buttons assigned to the C buttons and A button are ever touched by double checking your keybindings.

**Comment by Bradon-Lodwick** [comment]
Got it working, I believe it was the rom I had. Not sure why, I checked the version but maybe it was mislabelled on the site? Anyways thankyou
