### ISSUE TITLE
Gerudo Training Grounds Issue

### ISSUE THREAD

**Issue by technodudegh** [AmazingAmpharos/OoT-Randomizer#206]
I'm having an issue with logic in the Gerudo Training Grounds, mainly surrounding the Lens of Truth. The lens of truth is the reward for Darunia's Joy, and to get Darunia's Joy you need Saria's Song, which is located in the right side chest in the Gerudo Training Grounds. Now I'm playing with lens of truth being assumed required for all lens of truth chests, meaning the right side chest isn't accessible from the left side of Gerudo Training Grounds (If it's the chest I'm thinking of) because of where you use the lens of truth to hookshot to the switch and door. It's also not accessible from the right side since you can't scarecrow up there. The only other way I can think of to get there is through the key maze, but if I've already used the keys on the left side. then have I accidentally softlocked myself? Is there any way to get Saria's song? Thanks in advance for any advice you can give.
Here's the Log:
[OoT_R42JC9ANBACWAKAJAA_P76OOPV49P_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2659933/OoT_R42JC9ANBACWAKAJAA_P76OOPV49P_Spoiler.txt)

**Comment by flagrama** [comment]
You can play Song of Time in the lava room to get to the right side chests. You can get it by going a little deeper in the right side to the hammer chest.

I recommend you join the Discord if you have any further gameplay questions instead of making a bunch of invalid bug reports: https://discord.gg/pU2gBPc
