### ISSUE TITLE
Boots on DPad?

### ISSUE THREAD

**Issue by xathian** [AmazingAmpharos/OoT-Randomizer#209]
I'm not sure where else to ask this as I am just finding out about randomizers recently but I discovered this OoT randomizer about a week ago through a streamer. My question relates to a common thing I keep seeing, every time I've watched a livestream of this randomizer the chat always asks if the player is using the version of the randomizer that puts boot swapping on the dpad and if not recommend that he does so to save menu hopping time. I've seen it mentioned in the chat for runs by ZFG, Vinesauce, Tucans, Jepson, Versus, etc. It is always talked about every time I see a randomizer run. So I've been googling it and finding absolutely nothing on the subject (Literally 0 results that include both the randomizer and boot swapping in the same site), I looked through all the options in the randomizer and can't find anything. I figured maybe this was just twitch chat trolling but it's always brought up in every random stream I see so it seems legit. I checked the Dev branch here on github to see if it was in a beta version but it says the Dev branch is currently in a merged state with the stable so there's no different version in the dev branch.

Am I absolutely blind to this option in the menu or is this just some hardcore widespread trolling?

**Comment by flagrama** [comment]
This is only available in TestRunner's fork's Dev branch until 4.0. https://github.com/TestRunnerSRL/OoT-Randomizer/tree/Dev

**Comment by xathian** [comment]
Thank you
