### ISSUE TITLE
Where can i find 3.8.12 f.LUM?

### ISSUE THREAD

**Issue by Renzection** [AmazingAmpharos/OoT-Randomizer#211]
It says i need to update from 2.23.6 f.LUM but i cant find anything other then 4.6.8.
I'm not sure if this affects anything or not but im just trying to keep it all up to date.

**Comment by flagrama** [comment]
I don't know what 4.6.8 would even be referring to, but the latest version of the dev build (3.8.12 f.LUM as of this exact moment, cause it is sure to change) is on TestRunner's fork: https://github.com/TestRunnerSRL/OoT-Randomizer/tree/Dev

It is recommended you use https://ootrandomizer.com or the release build unless you are willing to accept the very great possibility of bugs, as dev is not 100% guaranteed to be stable.

**Comment by Renzection** [comment]
All i could find was a download for 4.6.8 f.LUM and not the current one being used, that was what i was refering to.
I didn't even know there was a website like ALTTP rando has, that's incredible. 
Thanks for the help ^^.

**Comment by flagrama** [comment]
4.6.8 doesn't exist yet for OOTR, and won't until a while after 4.0 has been released. I'm not sure what you found. That is where I'm confused.

EDIT: unless that's a typo and you mean 3.6.8 and just an older version of dev someone uploaded somewhere random.
