### ISSUE TITLE
Likely stuck because of Lullaby

### ISSUE THREAD

**Issue by CasualOcarinaPlayer** [AmazingAmpharos/OoT-Randomizer#212]
Hiya, casual OoTR player here, love playing and watching it. Think I found a loop and am stuck because of it. If I am missing something, please do point out my mistake, else I hope this helps in the future.

Summed up (log included):

OoT Randomizer Version v3.0  -  Seed: 6C0HOC56MT
Settings (R42JARSVGKBAAKAJSB)

all_reachable:                             True
logic_tricks:                              False
logic_windmill_poh:                        False
logic_zora_with_cucco:                     False
logic_zora_with_hovers:                    False

Bombchu Shop Item 5: Progressive Strength Upgrade
Windmill Freestanding PoH: Progressive Strength Upgrade
Bottom of the Well Underwater Left Chest: Progressive Strength Upgrade

Shadow Temple Invisible Blades Invisible Chest: Zeldas Lullaby
Spirit Temple Hallway Left Invisible Chest: Dins Fire
GS Zora's Domain Frozen Waterfall: Song of Time

[OoT_R42JARSVGKBAAKAJSB_6C0HOC56MT_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2688529/OoT_R42JARSVGKBAAKAJSB_6C0HOC56MT_Spoiler.txt)

**Comment by flagrama** [comment]
Do you have Boomerang? Boomerang is in logic for getting the Windmill PoH.

**Comment by CasualOcarinaPlayer** [comment]
Yep I'm an idiot, thanks for the quick reply, made it way more complicated than it should have been.
