### ISSUE TITLE
I can't even get a ROM

### ISSUE THREAD

**Issue by Enwyn-Rosethorne** [AmazingAmpharos/OoT-Randomizer#214]
The window at the bottom runs through all the usual processes, but then after it begins to compress the file, I get "[Critical Error] Exception thrown, see JavaScript console!
[Critical Error] Exception thrown, see JavaScript console!"

Any suggestions?

**Comment by flagrama** [comment]
It would be more effective to troubleshoot this on the [Discord](https://discord.gg/GyRhrUj) as this repository has very little to do with the website. The website just uses the randomizer in the background and is 100% known to work correctly.

But do be sure to mention what browser and OS you are using at a minimum.

**Comment by Enwyn-Rosethorne** [comment]
Alright, thank you. I am running on Mac, so that might be a bit janky.

**Comment by flagrama** [comment]
Well as a quick answer, Safari is known not to be supported. You'll have to use Firefox or Chrome. Beyond that, definitely ask the Discord.

**Comment by Enwyn-Rosethorne** [comment]
It was Safari. Thanks for your help!
