### ISSUE TITLE
Biggoron required and no Claim Check

### ISSUE THREAD

**Issue by tommaniacal** [AmazingAmpharos/OoT-Randomizer#216]
Biggoron's item is Mirror Shield, which I need to beat Twinrova, which I need to get Spirit Medallion. The spoiler log doesn't mention a claim check, and talking to biggoron and medigoron doesn't do anything.
[OoT_3416C_3GH40K2DEE_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2716988/OoT_3416C_3GH40K2DEE_Spoiler.txt)

Settings: BRGDVBAEH5WBAAAAUAGEFA
Seed: 3GH40K2DEE

**Comment by flagrama** [comment]
I assume you figured out it was the trade item/Pocket Egg you got from Child Fishing. But also, https://github.com/TestRunnerSRL/OoT-Randomizer is the proper place to report bugs with Dev currently.

I also highly recommend you join the Discord and ask if something is a bug in #gameplay-support before reporting anything here on Github.

**Comment by tommaniacal** [comment]
Yeah, I realized, haha. I forgot to set the earliest trade item. Thanks!
