### ISSUE TITLE
Unable to complete seed

### ISSUE THREAD

**Issue by aeonfusion** [AmazingAmpharos/OoT-Randomizer#222]
I left logic on but the game put the first hookshot upgrade at the 'goron city deku scrub deku nuts' item position, which i think is the lava room in goron city which requires hookshot. the next hookshot upgrade is in 'Shadow Temple After Wind Hidden Chest' which i haven't tried to get to yet but the spoiler log said i should get the hookshot upgrade from goron city next. anyways, just thought i'd let ye know. thanks for the randomizer, it's great fun

**Comment by flagrama** [comment]
Song of Time

**Comment by aeonfusion** [comment]
Yep, turns out i'm dumb and summoned one block but not the other, been a long time since i played this game :P Thanks for the advise flagrama. Funnily enough the seed is uncompleteable though, i'll try explain as best i can. 

-I have every medallion and stone apart from the Light Medallion and Zora Sapphire. 
-The Light Medallion is in the Fire Temple, the Zora Sapphire in the Shadow Temple
-In the Fire Temple i need the key to open the door in the invisible fire maze room to go from the bottom of the maze to the top so i can drop the pillar and cross the room into the boss room.
-In the Shadow Temple i need a key to open the door after you cross the statue which you drop using the bomb flowers in the room where you end up after the ship ride in order to proceed to the boss room.
-In order to get the key i need for the Fire Temple i either need to pick up the Ocarina of Time in the moat of Hyrule Town after i collect all three spiritual stones, the third of which is received by beating the Shadow Temple, or buy one from 'GC Deku Scrub Red Potion' which i can't access unless i beat the Fire Temple.
-In order to get the key to the Shadow Temple i need to get the Volviga heart container, which i can't access without getting the Zora Sapphire which is gained from completing the Shadow Temple 

As i only needed the Light Medallion to access Ganon's Castle i checked whether the game assumed i had it and created the bridge anyway but that didn't work. I'm not sure whether i used keys on doors which i didn't need to open in order to complete the dungeons or whether i can glitch passed these areas as i'm only a casual player. The spoiler log is attached so it should help. 

[OoT_R54RAQKZGKFUBKKJ3B_OTFPSIK6Q2_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2753720/OoT_R54RAQKZGKFUBKKJ3B_OTFPSIK6Q2_Spoiler.txt)

**Comment by flagrama** [comment]
You can fight Volvagia using hover boots if you have the boss key.

**Comment by rlbond86** [comment]
All these people who think their seed is not beatable... Come on guys, the randomizer is pretty smart...

**Comment by aeonfusion** [comment]
Hah, thanks flagrama for your help, much appreciated. 

rlbond86: I made the post as i thought the creators would like to know if there was any problems with the randomizer logic, not to be pointlessly critical :) thank you for your invaluable input though
