### ISSUE TITLE
Error while creating seed

### ISSUE THREAD

**Issue by SpaceKnigh7** [AmazingAmpharos/OoT-Randomizer#224]
Whenever I click "Generate Patched Rom", an error shows up saying:

   |-------------------------------------------------------------------|X|
   |    Error while creating seed                                                       
   |                                                                                                     
   |      (X) [WinError 2]  The system cannot find the file specified    
   |                                                                            OK                         
   |---------------------------------------------------------------------|

Please help me with this issue!

**Comment by flagrama** [comment]
Just a copy/paste from our Discord bot:

If you are experiencing the WinError2 problem - make sure of the following: 
- Extract all files from the 3.0 release zip (All of which are: OoTRandomizer.exe, compress.exe & decompress.exe) 
- Add the Randomizer folder to your antivirus exceptions/exclusions (Not sure how? google is your best friend) 
- Alternatively, you could add all 3 files individually to your antivirus exceptions/exclusions 
- The folder & programs possess read/write permissions 
- Don't have it in Program files 
- Be sure to Select Rom 
- Make sure your unzip your US 1.0 Base rom 
- Do NOT try to run the Randomizer from libraries or via a desktop shortcut. Run it from within it's folder!!

**Comment by SpaceKnigh7** [comment]
I just fixed it after reading that, thank you!
