### ISSUE TITLE
Black screen 

### ISSUE THREAD

**Issue by furdyeath** [AmazingAmpharos/OoT-Randomizer#228]
I'll download the patched rom and open it in project64 and nothing but a black screen.

**Comment by flagrama** [comment]
https://wiki.ootrandomizer.com/index.php?title=Project64

**Comment by furdyeath** [comment]
Well, step one and three don't happen but I think changing to Glide64 for PJ64 fixed it. Tho I did find one more bug but I think it's game being randomized where the bombchu lady had the Triforce story only she doesn't have the cut since so she's stuck saying din.... and the game it unplayable xD
