### ISSUE TITLE
Retroarch crashes upon opening first locked door in chest game

### ISSUE THREAD

**Issue by bampharos** [AmazingAmpharos/OoT-Randomizer#232]
Title.  Running compressed devbuild ROM on Mupen64Plus core.  Have not yet gotten to any other locked doors to see if it's a small key thing or just a chest game thing.

**Comment by flagrama** [comment]
This is a known issue with an old version of the dev build. 
1. This is not the repository for reporting issues with the dev build (and in fact it is recommended you ask about it in the Discord's questions channels first to make sure it isn't something already fixed) 
2. Make sure you are on the latest version of the dev build before reporting an issue.
