### ISSUE TITLE
cant find zeldas lullaby

### ISSUE THREAD

**Issue by cpissoff** [AmazingAmpharos/OoT-Randomizer#234]
trying as hard as i can not to look at the spoiler text, but i know its needed to help find the right location...
not sure what other info is needed besides this:

9: {
  Sheik at Temple: Zeldas Lullaby
  Fire Temple Boulder Maze Bombable Pit: Small Key (Fire Temple)
}

if more is needed, please let me know. thanks in advance!

**Comment by flagrama** [comment]
Get Forest Medallion. Walk up to Master Sword pedestal as Adult.

**Comment by cpissoff** [comment]
flagrama, thank you so much! i've literally spent a good 3 hours trying to figure this out!
