### ISSUE TITLE
Where is Bottom of the Well Front Center Bombable?

### ISSUE THREAD

**Issue by E-r-r-o-r** [AmazingAmpharos/OoT-Randomizer#238]
Where is it? The song of time is there, but I can't find it. I can't get into the locked door past the crawl space because I don't have enough keys, so I assume it's not there. It's not possible to get softlocked by using a key on the wrong door, is it?

**Comment by rlbond86** [comment]
Literally right when you walk in. Go past the skullltulla, and through the invisible wall. There is a bombable mound straight ahead, slightly off to the left.

**Comment by E-r-r-o-r** [comment]
Wow, I didn't know you could blow those up. Thanks so much
