### ISSUE TITLE
Need Zelda's Lullaby to get Zelda's Lullaby

### ISSUE THREAD

**Issue by DJTeeJay80** [AmazingAmpharos/OoT-Randomizer#242]
Seed URL: https://ootrandomizer.com/seed/get?id=138464

OoT Randomizer Version 4.0.0 Release  -  Seed: KLUAX7AB6F (glitchless)

File Select Hash:
    Boss Key
    Map
    Kokiri Tunic
    Deku Stick
    Hammer

Bottom of the Well MQ East Inner Room Freestanding Key:   Zeldas Lullaby

In the MQ-version of the BotW the central room is locked. To open the gates you have to play Zelda's Lullaby standing on the Triforce symbol on the outer ring. So how can I reach Zelda's Lullaby without Zelda's Lullaby?

**Comment by flagrama** [comment]
First ALWAYS ask in the discord first.
Second Side hopping over the pit in the area with the skulltula is in logic I think.
Third wrong repo: https://github.com/TestRunnerSRL/OoT-Randomizer

**Comment by flagrama** [comment]
```
"Bottom of the Well MQ East Inner Room Freestanding Key": "
                can_play(Zeldas_Lullaby) or has_explosives",
```
Yeah, that is definitely it. You blow open those rocks and sidehop over the pit. Just grabbed ZL in your seed so I can confirm this is the intended method.

**Comment by DJTeeJay80** [comment]
I've got it, thank you! But isn't that still against logic because I have to walk over an invisible path without the lens of truth to get there (impossible to get the lens of truth without Zelda's Lullaby because you need the longshot from the Ice Cavern)?

I think I've found a bug in the seed: When I went back to King Zora after solving the Ice Cavern the red ice around him had already disappeared.

One more question: Is it possible that I have to go into a softlock and reset the ROM - for example race against Dampe without the Song of Time and any Warp Song?

Sorry, but I didn't install discord because I don't know it.

**Comment by flagrama** [comment]
No. You are can be forced to do that in MQ under the more important "Worst Key Usage" rule randomizer logic follows.

King Zora unfreezing is a glitch present in the vanilla game.

Save and Quit is an intended mechanic. (Warp songs don't work in Dampe's grave regardless)

Github Issues is not the proper place for requesting help with a game. They are for actual bugs reported by people who are certain they are actually bugs. Usually the dev team or someone following the randomizer's development closely on Discord.

**Comment by DJTeeJay80** [comment]
Thank you for information! I was convinced to report an error because I had no idea I could overcome the pit with a sidehop.
