### ISSUE TITLE
"Open forest" broken. Seed requires kokiri forest/zora's river skip

### ISSUE THREAD

**Issue by justinbass** [AmazingAmpharos/OoT-Randomizer#246]
Not sure if this is by design, but this seed: 6XUCNL89T0 (settings string AJAGGGAAZ6FAAVGAAAAAEBNJLAA, link: https://ootrandomizer.com/seed/get?id=229249) is not beatable without major sequence breaking glitches.

Mido certainly requires a sword to pass, meaning "Open forest" is broken for me. I used a US v1.0 rom to patch, and all other randomizer features are working (and the game plays decently well). Patched through the public v5.0 oot randomizer website.

The kokiri's sword is in zora's river, but bomb bags/bombchus to open the pathway are clearly not accessible at this point. I categorically extended all chests, grottos, games, and legally explorable parts of the map and barring a redefinition of the word "glitch", this seed is impossible without glitches.

This is also obvious looking at the spoiler log's spheres, showing the player stuck at sphere 0, as advancement to sphere 1 (deku tree) requires a kokiri sword (to pass mido) or the bombs (to get the sword). The only items usable as a child in sphere 0 are the slingshot, deku shield, deku nuts, and the adult wallet. You cannot buy bombs or bombchus, or obtain them in any other way.

Fortunately the glitch/skip is possible and fairly easy, but this behavior is confusing and not noted anywhere, also requiring me to read the entire spoiler log and reducing my trust in the rest of the game for this seed. I didn't touch any of the vanilla settings, so a glitch-requiring seed is even more unexpected.

Let me know if this was in error, or if you cannot replicate. I can send the original and patched roms at request.

**Comment by flagrama** [comment]
This is not the current development repo, and please go to the Discord's #gameplay-support channel to get someone to direct you to what you missed in your seed because there is almost no way to get a softlocked seed.

https://discord.gg/vM4uR4s

**Comment by flagrama** [comment]
You have open forest on. There is no Mido. If you are using Project64 it is garbage and you should use Bizhawk or Retroarch instead.

**Comment by rlbond86** [comment]
You are probably using an unsupported enulator and did not fully delete your old Ocarina of Time save file.

**Comment by justinbass** [comment]
Mido is there (do I really need to screenshot this?), and all other spoiler log output shows that the ROM was at least partially patched successfully. Deleting the old save file, and mentioning that Project64 is not just discouraged but simply unsupported is not mentioned in the documentation, and should be as it's not at all clear that the vanilla default settings would be plain broken on the most common emulator in existence. Let alone mentioning this on the public website that 99% of users are likely to land on. Just a suggestion.

**Comment by justinbass** [comment]
Also if this isn't the main dev repo, why isn't that the first thing mentioned in the Readme? Categorically dismissing real issues and not supporting major use cases is not a great dev strategy. Your team should be grateful that users (and experienced SDEs) care enough about this project to take the effort to file bug reports, even if there is a lot of noise. No offense intended, we all know this is open source and the project is great for what it is.

**Comment by flagrama** [comment]
On Mon, 2019-09-02 at 21:57 -0700, Justin Bass wrote:
> Also if this isn't the main dev repo, why isn't that the first thing mentioned
> in the Readme? Categorically dismissing real issues and not supporting major
> use cases is not a great dev strategy. Your team should be grateful that users
> care enough about this project to take the effort to file bug reports, even if
> there is a lot of noise. No offense intended, we all know this is open source
> and the project is great for what it is.

We have over 30,000 users in our Discord. This stuff has been repeated over and
over again. The Discord is our main method of support while the bugs are
generally imported from the Discord to the repo by the devs as users are easily
confused over how certain things work and are quick to jump to the conclusion
that something in the code is wrong when generally it's just their
misunderstanding.

I don't know why AA has never mentioned that all dev is presently happening on
the TestRunnerSRL fork, but I have no control over what he chooses to do. But
the fact of this matter is that this repo is 2000 commits behind the actual repo
being used for Dev.

Project 64 is a absolute last resort for users whose computers can not handle
the Bizhawk or Retroarch emulators. From our Discord bot (again our primary
method of support)

> Project64 has some known compatibility issues with the randomizer. It's for
> this reason that we highly recommend only using it as a last resort, if your
> computer can't handle any other emulators. 
> 
> We suggest using Retroarch or Bizhawk:
> https://wiki.ootrandomizer.com/index.php?title=Retroarch
> https://wiki.ootrandomizer.com/index.php?title=Bizhawk
> 
> PJ64 uses its own code in the background of emulation in order to attempt to
> make the game run faster and at a higher quality. The problem is, this custom
> code is only for vanilla ROMs, and so it has some trouble dealing with
> ROMhacks such as the randomizer. This can lead to some known crashes and
> graphical issues, such as a crash when draining the well at night, and when
> entering the adult kakariko shops. 
> PJ64 also names its save files according to the name of the game itself,
> instead of according to the ROM's filename, like Bizhawk or Retroarch. This
> can lead to corrupted save flags when dealing with multiple save files. It's
> for this reason that you must delete your PJ64 .sav file every time you create
> a new seed. 
> 
> If using our recommended emulators is not an option, please refer to the
> following guide: 
> https://wiki.ootrandomizer.com/index.php?title=Project64

We appreciate bug reports, but as you can imagine, we're not fond of getting the
same one, quite literally, 10,000 times. Fixing Project64 would require actually
modifying PJ64, not changing anything in the rando.

**Comment by justinbass** [comment]
I've heard PJ64 doesn't support romhacks well, my points are more focused at documentation. Unfortunate that this outdated repo currently pops up first in Google search, having double the stars as the TestRunner fork. Anyways I can continue in the discord chat if I see anything undocumented (also unstarred this, starred the other one). Thanks for the detailed reply.

**Comment by justinbass** [comment]
Would like to update that I completed an entire randomized game in Project 64 v2.4.0.973-geace1a7 without any issues, except the aforementioned issue which actually has nothing to do with Project 64, but is instead a common issue that can occur with any emulator, likely a soft-bug/documentation-gap in the randomizer generation due to save files being shared between the OoT-vanilla ROM and the OoT-randomizer ROM. There were minor graphical issues which did not affect gameplay.
