### ISSUE TITLE
Getting Zelda's Letter before any Ocarina.

### ISSUE THREAD

**Issue by shoover56** [AmazingAmpharos/OoT-Randomizer#34]
Seed 60420181.

I'm currently playing through this right now and nobody I've asked that has played this had any idea if intended or self-corrected, so I figured i'd post in case it turns out it is a bug or renders my playthrough incompletable.

My seed gave me silver scale from Mido's house and Kokiri Emerald on file creation, but I did not get Saria's Ocarina, instead I escaped through the Forest, using the Silver Scale diving, and through a series of unrelated findings, allowed me to go get Zelda's Letter without an Ocarina at all.

Normally after you get the letter and leave, you talk to Impa to learn a randomized song, however because I didn't have an Ocarina, Impa wasn't there and I didn't learn anything. I also could not come back after getting Ocarina, as per normal logic, the guards would block you after going through the crawlspace into the castle.

I'd just like to know for clarity if this is intended or if I'm going to learn the what would be song sometime later. Thanks!

**Comment by CMuncey** [comment]
Impa should definitely be there even if you don't have the Ocarina, Link will just pull out an Ocarina anyway. Are you on the normal release, or the dev branch?

**Comment by shoover56** [comment]
@CMuncey Normal release.

**Comment by shoover56** [comment]
I'm gonna go ahead and close this because I regenerated the rom with the spoiler log and it says that I got Sun's Song from Impa even though I didn't see Impa. I do have it learned. If I come across this issue again, I'll reopen it.
