### ISSUE TITLE
Broken Logic

### ISSUE THREAD

**Issue by robertvanderaarde** [AmazingAmpharos/OoT-Randomizer#4]
This streamer could only get the mirror shield, hookshot (longshot was received by glitching into forest early), and iron boots  in Ganon's castle. To enter there he had to bombchu hover in before the bridge was opened.
This was in medallions mode.

https://clips.twitch.tv/BoldLongBeefKevinTurtle

**Comment by AmazingAmpharos** [comment]
That seed was generated on an older version of the logic using a setting that was not supported at the time (the "vanilla" logic for Rainbow Bridge creation before I had the right conditions set for it). Unfortunately some poor community communication resulted in it being played when it really never should have been. I'm sorry for the inconvenience that created.
