### ISSUE TITLE
[Suggestion] Mentionning that patched rom are for Emus and VC

### ISSUE THREAD

**Issue by Niamek** [AmazingAmpharos/OoT-Randomizer#41]
In the latest dev build, it looks like this: https://media.discordapp.net/attachments/274186223147417600/457582620142862337/unknown.png?width=566&height=336

I'd change "Compress patched Rom" to "Compress patched Rom (For VC and emus)".

I think it be a neat change to reduce the amount of people having problem with opening non compressed roms. Small and simple text change from what I can see.

**Comment by AmazingAmpharos** [comment]
I'll have to play with the wording here to keep the GUI compact but the general idea is good.
