### ISSUE TITLE
can't equip hylian shield with certain inventory layout

### ISSUE THREAD

**Issue by amberflemingf** [AmazingAmpharos/OoT-Randomizer#44]
![hylian shield](https://user-images.githubusercontent.com/37123522/41577309-2a38ef96-735a-11e8-937e-1d05333db41e.PNG)
i cannot select the hylian shield here to equip it. hylian shield found in chest and not purchased, if that matters. using dev branch. bps of the seed and sram with the inventory displayed attached.
[test.zip](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2113855/test.zip)

**Comment by CMuncey** [comment]
Buy a kokiri shield

**Comment by AmazingAmpharos** [comment]
This is known and will probably be fixed post-2.0. You can always get out of the situation currently by acquiring all of Master Sword, Deku Shield, and Hylian Shield which are in static and generally obtainable places, but it's a general problem with the vanilla game.

**Comment by AmazingAmpharos** [comment]
Fixed in 3.0.
