### ISSUE TITLE
2.0 requires python 3.6

### ISSUE THREAD

**Issue by gjgfuj** [AmazingAmpharos/OoT-Randomizer#45]
random.choices, which is used in the dev branch for randomizing the colours of tunics is added in 3.6. this is easy to fix to work on 3.5 by simply not using Random tunic colour and commenting the one line in Rom.py where it is used out, but otherwise you should specify that it requires 3.6. just letting you know.

**Comment by AmazingAmpharos** [comment]
I'm keeping this open and commenting here to remind myself to make this very clear in the readme for the 3.0 release.

**Comment by phixtyseven** [comment]
It seems this is about settled, however I'm noticing a bug in running `Gui.py` with Python 3.5. The combo box options seem to be mixed up. It's different each time, which leads me to believe the random module is involved. What I don't understand is why the settings themselves are getting shuffled.

**Comment by flagrama** [comment]
> It is best to think of a dictionary as an unordered set of key: value pairs,
> https://docs.python.org/3.5/tutorial/datastructures.html?highlight=dictionary

Before 3.6 Python dictionaries were not ordered in any way.

> From Python 3.6 onwards, the standard dict type maintains insertion order by default.
> https://stackoverflow.com/a/39537308

But it appears 3.6 changed this behavior, and the previous quote from the documentations appears to have been removed entirely for 3.7

**Comment by AmazingAmpharos** [comment]
Python versions handled I think well in 3.0.
