### ISSUE TITLE
Suggestion: an option to disable the randomization of songs

### ISSUE THREAD

**Issue by ashelleyPurdue** [AmazingAmpharos/OoT-Randomizer#49]
It's pretty tedious to go through so much of the game without Prelude of Light or Epona's Song.  I can't warp to switch from adult to kid, nor can I use Epona to get anywhere fast.  It's torturous!

I would LOVE the ability to keep those two songs in their normal places...or at the very least in places that are always easily accessible.

Perhaps for the Prelude of Light, it can be learned without needing the forest medallion.

**Comment by AmazingAmpharos** [comment]
I understand that sometimes the randomizer can be inconvenient, but it's kinda the nature of things. It's worth noting that Epona's Song doesn't really save much travel time (Epona is not as fast as you think when you consider the summon time versus just backwalking the field) and the adult can savewarp to the Temple of Time which can help deal with not having Prelude of Light (if you have Nocturne it's not a terrible walk for the kid from Kak to the Market). In general though every song can be useful for different things (there are no worthless songs), and while you might miss having some songs, you can often make excellent use of the other songs you get instead. I feel fairly strongly that the songs being randomized is critical to the gameplay depth of the randomizer, and for that reason, such an option is unlikely to be implemented.
