### ISSUE TITLE
Run Down Tower with Fast Ganon Option

### ISSUE THREAD

**Issue by RobertM-13** [AmazingAmpharos/OoT-Randomizer#51]
If you die during the Ganon fight, the Game Over forces you to run down the tower instead of skipping that portion as it does when you first defeat Ganondorf.

**Comment by AmazingAmpharos** [comment]
It's a known issue. It's pretty hard to actually die to Ganon (he's not very dangerous), but it's something we'll be looking into fixing for the next release as it is indeed awkward.
