### ISSUE TITLE
Unbeatable seed?

### ISSUE THREAD

**Issue by denoflionsx** [AmazingAmpharos/OoT-Randomizer#52]
Seed: 332001748
Settings: medallions-openforest-fastganon
Spoiler log enabled.

Maybe I'm failing to understand something, but it placed the longshot in a chest in that requires the longshot to reach (Gerudo Training Grounds Before Heavy Block Chest). Someone please correct me if I'm wrong... I threw in the towel on the seed due to not being able to get longshot. I swear I've searched the place top to bottom and came up empty before posting this... consulting every guide known to man.

[OoT_medallions-openforest-fastganon_332001748_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2136275/OoT_medallions-openforest-fastganon_332001748_Spoiler.txt)

![image](https://user-images.githubusercontent.com/1806869/41900038-c5c5d432-78fb-11e8-84e6-ea132463a30c.png)

**Comment by Geisterwand** [comment]
Which room is this in specifically? You can full clear the training grounds without the Longshot (did it just today).

**Comment by AmazingAmpharos** [comment]
Stand directly under the Hookshot target under the silver rupee. Hookshot is long enough, but you just can't shoot at a very diagonal angle to make it.
