### ISSUE TITLE
Question: DAG?

### ISSUE THREAD

**Issue by KevinTyrrell** [AmazingAmpharos/OoT-Randomizer#53]
Did you use a Directed Acyclic Graph topological sort algorithm to figure out item priorities to make sure while randomizing, that the player can still progress. I haven't had time to look through the source. Would love to know your approach for how you did this. 

Thanks.

**Comment by JedGrabman** [comment]
Not a dev, but I've spent a while playing with the code.
Several items are considered progression items, these are things like the iron boots that allow you to access new areas and progress through the game. These items are placed before things like rupees, etc. The actual process for placing the items is essentially:
1. Choose a random progression item that has not yet been placed and remove it from the non-placed items list
2. Determine which locations are reachable with a combination of non-placed items, and items that may be reached if you started with the non-placed items.
3. Place the item in one of these locations

At the start of the process, no items have been placed, but it is assumed the player will be able to collect all of them, and thus beat the game. Once one item is placed, it is ensured that the placed item can be collected by the remaining items, and the game is still beatable, thus all items may be collected and the game is still beatable. When the second item is placed, it is ensured that it can be collected and therefore the first item is also collectible. Thus, at the end of the process it is ensured that the last item to be placed can be collected and therefore the second to last item to be placed can be collected and therefore ... the first item to be placed can be collected, so all items are collectible. This ensures the game is beatable.

To clarify, the items are not necessarily collectible in the order that they are placed. For example, if the boomerang is locked behind the bow, there are two possibilities. Either the boomerang was placed first and it was ensured that the bow could be collected without it, or the bow was placed first and it was known that it could be reached without the boomerang, so the boomerang could be placed behind the bow without a problem.

Dungeon keys are placed in essentially the same manor, but ensuring they are in the proper dungeon. This takes place before the progression items are placed.

Figuring out where items can be placed is essentially a graph search where what items you have determines which edges can be traversed.

Medallions, stones and songs are all determined before this, but are pretty much just random.

**Comment by AmazingAmpharos** [comment]
Jed's explanation is essentially correct with a few minor notes. The order of operations is Medallions/Stones then Songs then Boss Keys then Small Keys then Maps/Compasses then progression items then Ice Traps then junk items (junk items being defined as anything that is always irrelevant to logic; it could still be a good item like Nayru's Love or Double Defense). Medallions/Stones, Maps/Compasses, and junk items are placed without any logical considerations other than being put into the right location set and the locations being empty before they're put in. Songs, progression items, Boss Keys, and Small Keys use the full logical considerations listed. Ice Traps use an abbreviated set of logic that amounts to "only put Ice Traps into chests" which is necessary for them to actually work (we used to have to limit other types of junk items too as they tended to break NPC scripts, but the override system in 2.0 takes care of all the other cases so now it's just Ice Traps).

The general algorithm is borrowed from the Link to the Past Entrance Randomizer. The basic concept of the algorithm was originally written by LLCoolDave, has been tweaked a bit within lttp (and is now the underlying algorithm for all lttp randomization), and was tweaked further for this project. That randomizer can be found here if you're curious:

https://github.com/AmazingAmpharos/ALttPEntranceRandomizer

I'll admit that I'm not really savvy to the tech jargon here, but I hope that you've gotten a good explanation for how it works. I'll leave this open for a bit in case anything was unclear and then I'll be closing it up in a few days.
