### ISSUE TITLE
Nocturne not obtainable as child

### ISSUE THREAD

**Issue by Hamsda** [AmazingAmpharos/OoT-Randomizer#54]
https://github.com/AmazingAmpharos/OoT-Randomizer/blob/f9abb00a299e2f50f52fee4962047f8ab7f84975/Rules.py#L229

As posted by squirleon#9378 on discord, he had a closed door seed that was unbeatable because it required him to get SoT from Nocturne location.

[OoT_medallions_395157844_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2159269/OoT_medallions_395157844_Spoiler.txt)

**Comment by AmazingAmpharos** [comment]
That was fixed, for 1.0 in fact. Somehow that fix got reverted which makes me very nervous about what else in the logic got broken that should be fixed. I'll be investigating, but that does explain a lot about another such issue I'd be informed of.

**Comment by AmazingAmpharos** [comment]
Okay, this issue will remain open for now but I've pinpointed what's going on and this is indeed an isolated issue. This will be fixed for the next update.
