### ISSUE TITLE
Questions: Contact / Discord & Minor Model Editing

### ISSUE THREAD

**Issue by InTheBeef** [AmazingAmpharos/OoT-Randomizer#55]
Would it be possible to setup a Discord Server (Assuming there isn't one already) for better communication between players of the discord &/or devs. There do not appear to be any methods of contacting the developer besides GitHub.

Also wondering how feasible it would be to add further player customization options to the Randomizer, such as some basic vertex/texture edits and if those begin to introduce any lag (assuming no changes to file size are made).

Thank you.

**Comment by AmazingAmpharos** [comment]
A discord does exist.

https://discord.gg/AbdmNWn

We haven't really investigated non-trivial graphics editing at this point, but indeed, we wouldn't be okay with any non-gameplay changes that affected lag at all or had any impact on collision/gameplay interactions which could make it a tricky process.
