### ISSUE TITLE
Fire Arrow x2

### ISSUE THREAD

**Issue by CodyNorthrup** [AmazingAmpharos/OoT-Randomizer#57]
Received the Fire Arrow twice in the beginning at Mido's House. Not sure if game breaking as I just started

**Comment by ThamanVelasquezBice** [comment]
Did you generate a spoiler file with this save? Also did you happen to proceed into this save? Was it an issue?

**Comment by CodyNorthrup** [comment]
I did for a little while. It ended up crashing. I have since downloaded the
most recent version and it has gone off without an issue. I was running the
first version of the randomizer.

**Comment by ThamanVelasquezBice** [comment]
Gotcha. I was mostly curious to know if the issue was fixed, and if fire arrows was listed twice on the spoiler sheet

**Comment by AmazingAmpharos** [comment]
A strange issue, never seen or heard of anything like it. The code has changed a lot since this was reported so I'm going to just close it.
