### ISSUE TITLE
Cannot find last key in Ganon's Castle, locked out of the room the leads to the light barrier!

### ISSUE THREAD

**Issue by 03bgood** [AmazingAmpharos/OoT-Randomizer#61]
I've checked every chest and all of them have been opened. I even did the barrier skip and made to the floor with the chest that would normally spawn the boss key, instead it was only arrows. Am I fucked?

I can't open the door that leads to the cylinder room with the boulders and silver rupees. After that is the light barrier room after going through the fake wall.

**Comment by JedGrabman** [comment]
What's the seed number?
What settings did you use?
What version are you on?
Do you have a spoiler log?

**Comment by 03bgood** [comment]
Had to use game shark to bypass locked door. I have no idea why the small key hadn't spawned but in my second quest, I didn't get locked out of any dungeon.

**Comment by SheridanR** [comment]
Had the same thing happen to me. Opened every chest I could find in the castle, but no key.

Version: 2.0.0
Seed: 768345834567
Settings: open forest, open door of time, place dungeon items, bridge: medallions, tunics: all random, low health sound: mweep

Hopefully somebody more experienced with the game can find it.

**Comment by flagrama** [comment]
You guys have definitely opened the invisible chest in Spirit Trial right?

**Comment by AmazingAmpharos** [comment]
The two small keys in the most recently posted seed are in the Lullaby chest in Light Trial (so behind the first key) and in the second chest in the Spirit Trial which is indeed that easy to miss invisible chest near the torches and the switch you hit from the other side of the fence with a Bombchu.

As per the earlier issue, in general requiring items that used to be lategame items earlier is intended randomizer behavior; the randomizer's nature is changing the game's sequence, and Hover Boots especially are an item that can be used in many ways much earlier in the game than Shadow Temple from vanilla.
