### ISSUE TITLE
Locked into Child, cannot progress

### ISSUE THREAD

**Issue by TayroWinters** [AmazingAmpharos/OoT-Randomizer#62]
Seed: 850022522

Rainbow Bridge Requirement:      medallions
Open Forest:                     No
Open Door of Time:               No
Fast Ganon's Castle:             Yes
All Locations Accessible:        Yes
Maps and Compasses in Dungeons:  Yes

Generated with log.

-------

Generated this game to play today, have an issue regarding songs. Given I'm playing with closed Door of Time, I require the **Song of Time** to open it. I get the Song of Time from the **Composer's Grave**, which means I require **Zelda's Lullaby**. I get Zelda's Lullaby from **Sheik in Kakariko** as an Adult.

...as such, I'm locked into Child and cannot progress in the game.

**Comment by TayroWinters** [comment]
Oh, my bad. Didn't realize it was the same. It also has happened again with seed 740065876, under the same settings except for Maps & Compasses in Dungeons, which was set to 'No'.

Is there a means to apply an 'Open Door of Time' to an already randomized game without altering what was already set?

**Comment by AlessandroPorcelli91** [comment]
A similar issue happens in seed 88, you can't obtain the song of time as a child, you get it from mr Dickinabox in the mill (as an adult).
