### ISSUE TITLE
Unbeatble Seed #7897118105

### ISSUE THREAD

**Issue by csharporbflat** [AmazingAmpharos/OoT-Randomizer#65]
ok, so there is a bug, in this seed you need to get to the colossus, to get the requiem. You need the longshot to get to the colossus, and the progressive longshot in in the desert fairy. So it is impossible. Settings were all dungeons, compressed file, open door of time, open forest. Think so additional logic needs to be programmed in to prevent the sort of thing

**Comment by Niamek** [comment]
You can use Epona as well.
