### ISSUE TITLE
Unable to reach DMC without explosives

### ISSUE THREAD

**Issue by rchrm5** [AmazingAmpharos/OoT-Randomizer#67]
[OoT_open-openforest-opendoor-fastganon_903230890_Spoiler.txt](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2239564/OoT_open-openforest-opendoor-fastganon_903230890_Spoiler.txt)
Maybe I'm missing something, but the spoiler file attached assumes that one can reach Death Mountain Crater without Bolero, explosives, or the hammer. Am I missing something? Check branch 2.

**Comment by Glimmerglaze** [comment]
You can stop Link the Goron (and open Darunia's chamber) with bomb flowers, so the Strength 1 upgrade and the Hookshot are enough to get you the Bolero location.

**Comment by rchrm5** [comment]
I realized my oversite soon after posting. Thanks!
