### ISSUE TITLE
"Executing from non-mapped space. Verify ROM and ROM Settings."

### ISSUE THREAD

**Issue by radTad15** [AmazingAmpharos/OoT-Randomizer#68]
i get this when i try to run the randomizer ROM

**Comment by Niamek** [comment]
Instead of opening an issue here, try getting help over there first: https://discord.gg/mR6Y8W3

I can't help you sadly. Good luck!

**Comment by AmazingAmpharos** [comment]
This is ancient and my bad for not watching this for months, but this is a pj64 issue. You need to increase the RAM from 4 MB to 8 MB in settings for that particular ROM. pj64 is bad. Anyone else with this exact same issue should know this.
