### ISSUE TITLE
Generate Spoiler Appears Incorrect...

### ISSUE THREAD

**Issue by CascadeHope** [AmazingAmpharos/OoT-Randomizer#69]
Seed: 186248268
Settings: medallions-open forest
Spoiler Log Disabled

I started a randomized run today, with the following settings;

![image](https://user-images.githubusercontent.com/42064090/43638655-eae43170-96d6-11e8-9377-9fde2a1d443e.png)

However, after going everywhere I can think of... I haven't been able to make any steady progression. (Missing Slingshot so can't complete Deku Tree or Dodongo Cavern, Missing Ruto letter so can't enter Jabu Jabu, Missing Saria's Song, etc)

So I tried to generate a spoiler for the same seed. It generated incorrectly though.. (Link's Pocket - Spirit Medallion, when should be Water Medallion)..

I see that Spoiler Log lists "Affects Item Layout".. But is there a way to generate a spoiler to the correct layout?

**Comment by ThamanVelasquezBice** [comment]
Out of curiosity, when you go speak to the gem stand in the temple of time, what does it say is in your pocket?

**Comment by CascadeHope** [comment]
I'm not sure what you mean... it says "Ye who owns 3 spiritual stones... One inside a goddess of the sand. One on a high mountain. One inside an ancient tree... Stand with the Ocarina of Time and play the Song of Time.

**Comment by Niamek** [comment]
When you check generate a spoiler, the entire randomization is changed. So you're out of luck.

This is to prevent cheating in races.

**Comment by eeliottheking** [comment]
> Not sure why I closed this earlier... I made progress, but that didn't solve the issue with the inability to generate a spoiler file.

As Niamek said, you cant get a spoiler file as this is a security precaution for races.  If you are stuck feel free to head over to the discord and ask for help! https://discord.gg/rUCTS6
