### ISSUE TITLE
Gerudo Training Grounds unobtainable final key

### ISSUE THREAD

**Issue by Hydrochoerus** [AmazingAmpharos/OoT-Randomizer#70]
Playing with seed #777 with the following options (2.0 release):
Rainbow Bridge: dungeons
Tunics: True random
Health SFX: random

Place dungeon items: true
Other options on gui's right side: false

I was playing the Gerudo Training Grounds and was expecting to be able to open all the chests, no matter the order I open the locked doors. Turns out that the big chest in the treasure chest room can contain a small key. If the player spent the other keys before opening the final door, the big chest can not be opened. This is not really a problem, but can confuse the players before they realize that the final chest must contain the last key.

**Comment by rlbond86** [comment]
This also can happen in the water temple, if a small key appears in the boss chest you can get locked out. Personally I think the rules should be updated to disallow keys in dead ends behind locked doors to avoid this...

**Comment by AmazingAmpharos** [comment]
This is by design. Key for key just allows for more diverse chest layouts while not blocking you from any actual items (since the use of the key is negated by you not being able to reach the room it's in).
