### ISSUE TITLE
Boss key not found in Ganon's Castle

### ISSUE THREAD

**Issue by 03bgood** [AmazingAmpharos/OoT-Randomizer#71]
I'm locked out of the door that takes you to Ganondorf! I opened every single chest and I have no boss key. What do I do? Gameshark is the only workaround.

On my first playthrough, I was cheated out of key, now it's the boss key. The stupid boss key chest only had a gold rupee.

I think there's a gamebreaking glitch that causes either a small key or the boss key in Ganon's Castle, not to spawn in a chest, thus making it impossible to proceed.

There needs to be a patch, where all small keys and boss keys are not randomized. It would prevent gamebreaking glitches.

**Comment by Niamek** [comment]
Did you open the invisible chest in spirit trial.

The randomizer is already trying to prevent that, so you must have forgot one chest. Look harder. :)

**Comment by 03bgood** [comment]
Wow, I had no idea there was an invisible chest in the 2nd room of the Spirit Trial! It did have the boss key.
