### ISSUE TITLE
rom will not work

### ISSUE THREAD

**Issue by sirfreezealot** [AmazingAmpharos/OoT-Randomizer#72]
it dose not work on win32

**Comment by etaylor8086** [comment]
Your issue is pretty vague. Does the randomizer program not run? Are you able to generate a rom but not able to run the game in an emulator?

**Comment by ChrisMuncey** [comment]
Probably the compressor. That's known, I'm working on getting a 32 bit version working..

**Comment by sirfreezealot** [comment]
it cant read the compressor.  it says not conpatible

**Comment by CMuncey** [comment]
Steal the compressor/decompressor from this fork (https://github.com/CMuncey/OoT-Randomizer) and replace your existing one with it. Use the Compress32 and Decompress32 files though, those are the 32 bit version ones.

**Comment by sirfreezealot** [comment]
thanks
