### ISSUE TITLE
Missing a key in Light Trial in Ganons tower

### ISSUE THREAD

**Issue by TheMrRuckus** [AmazingAmpharos/OoT-Randomizer#74]
Missing a key somewhere in Ganon's tower. have checked the spoiler file and it says that there's only 2 keys when you need 3 to beat first part of the tower. Have no idea how to get past this.

The first room with the large amount of chests had 1 key and the lullaby room had the boss key.

Ive beaten all of the other Trials but this one and Ive triple checked for chests Ive missed as well. Is it an unbeatable key?

**Comment by Niamek** [comment]
Have you tried the hidden chest in spirit trial?

**Comment by TheMrRuckus** [comment]
If you're talking about the one in the room that you need the Bombchus in then yes I did. If not then I have no idea what chest you mean.

**Comment by Niamek** [comment]
I'm pretty sure you need only 2 keys by the way. There is 2 locked doors in light trials, not 3.

**Comment by Niamek** [comment]
If you have a discord account I suggest you ask around in the discord server of the randomizer. Plenty of people will help you. It will also be faster than here.

**Comment by AmazingAmpharos** [comment]
To clarify as I close this, Ganon's Castle only has 3 small keys in Master Quest. In vanilla it only has 2 small keys.
