### ISSUE TITLE
randomizer creates compressed rom with 0kb file size.

### ISSUE THREAD

**Issue by WillTereika** [AmazingAmpharos/OoT-Randomizer#75]
Subject says it all. Every time I try to create a compressed rom (which from what I read is required for most emulators to run it properly) it creates a normal rom, and a compressed rom with 0kb file size.   I'm on a windows 10 machine, so its a 64bit system.. any way to fix this?

**Comment by flagrama** [comment]
Windows 10 does not imply 64-bit. Windows 10 has 32-bit versions as well.

Another issue that can occur is if you close the command prompt window that appears while creating a ROM you will cancel the compressor which will leave a 0kb file.

**Comment by WillTereika** [comment]
I know 32 bit windows 10 does not exist.. so I'm guessing that is the issue?  So I need to downgrade my OS just to play this?

**Comment by CMuncey** [comment]
There is a 32 bit compressor in [this repo](https://github.com/CMuncey/OoT-Randomizer). To get it, download that version, then take "Compress32.exe" and "Decompress32.exe", and place them in the appropriate "Compress" and "Decompress" folder. Rename them "Compress.exe" and "Decompress.exe" (without the quotes) This will overwrite your existing executables, but that's fine. After that, you should be good to go. There's an update coming soon™ that will include detection and support for 32 bit systems natively, but at the moment, you'll need to do that.
