### ISSUE TITLE
Multiple duplicate items

### ISSUE THREAD

**Issue by nyrdagur** [AmazingAmpharos/OoT-Randomizer#77]
My randomized ROM has given me multiple copies of items. Specifically, I started off with the forest medallion but also received it for beating one of the dungeons. I've also taught the Song of Time twice, and just received ice arrows for the second time. I'm particularly afraid I won't be able to get all the medallions now. I've tried to generate a spoiler log after the fact, but I didn't use a seed and stupidly renamed the file. Is there still a way to make a spoiler log?

I didn't check "ensure the seed is beatable" when generating it, is this a natural consequence of that? Otherwise, the only other explanation I can think of is that I have on my Pi an earlier patch that I tried and gave up on because I hadn't opened the forest. (In fact, I think they may share save files.)

**Comment by Niamek** [comment]
Make sure to delete every saves related to oot rando before playing a rando. From what I've seen in the discord channel, this was the issue.

**Comment by nyrdagur** [comment]
Thanks for confirming my suspicions. I deleted all the former saves and have started a new patch without any trouble so far.
