### ISSUE TITLE
can't open the directory

### ISSUE THREAD

**Issue by lobos716** [AmazingAmpharos/OoT-Randomizer#79]
i have tried many versions of python but none of them will run the Gui.py file, it just come up with modify, repair, or uninstall but none of these option do anything for the file. Am i missing something? I've been trying many things but nothing i do gets the randomizer to open.

**Comment by CMuncey** [comment]
If you download the release, then you don't need python. It will install as an executable that you can launch.. unless you just want to use python for whatever reason..
