### ISSUE TITLE
randomizer to work

### ISSUE THREAD

**Issue by acer85** [AmazingAmpharos/OoT-Randomizer#80]
randomizer is not  work for me  have 32-bit system
![capture](https://user-images.githubusercontent.com/42472883/44273000-45411300-a20c-11e8-9e4e-fb5e0813d5f6.GIF)

**Comment by CMuncey** [comment]
Go to this fork: https://github.com/CMuncey/OoT-Randomizer

Download it as a zip file, take "Compress32.exe" and "Decompress32.exe" from that version, and place them in your randomiser's Compress and Decompress folder. Then rename them "Compress.exe" and "Decompress.exe" (without the quotes). This will replace your existing files, but that's fine. After that, it should work. This compressor is also the updated version, so it should be a lot faster on the second run than your current one would be.

**Comment by acer85** [comment]
i try it but to no  good some thing
