### ISSUE TITLE
Unbeatable seed?

### ISSUE THREAD

**Issue by XANA520** [AmazingAmpharos/OoT-Randomizer#83]
I believe I have found a conundrum of a problem. The seed I am playing has ground to a halt and I decided to check the progression log. If I am reading this right, the logic seems to want me to get the Lake Hylia Sun item, which I assume means the fire arrows that have been replaced with the hammer, so I can go beat the Fire Temple. However,

I cannot get the Lake Hylia Sun item because I have not beaten the Water Temple,
I cannot beat the Water Temple because I don't have Zelda's Lullaby,
I can't get Zelda's Lullaby because I can't get the Forest Medallion, and
I can't get the Forest Medallion _because it's in the Fire Temple_.

I've read that if the Boss Key to the Water Temple is in the Map or Compass chest, you don't need Zelda's Lullaby to beat it, but it's not there. It's in the chest behind the bombable wall just above where you meet Ruto in the main game. I've opened the wall with a cooked Bombchu from above, but you can't open chests underwater. Also I've run out of keys in the Fire Temple due the game only giving me 2 keys and 50 rupees before I got to the maze room: the locked door at the top of the fire-block elevator is the big obstacle. Is this seed completely unbeatable or am I missing something?

[OoT_open-openforest-opendoor_375187692.zip](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2300142/OoT_open-openforest-opendoor_375187692.zip)

**Comment by emerald000** [comment]
If you have the Longshot, you can call Pierre next to the Fire Arrows chest and hookshot up. You don't have to complete the Water Temple.

**Comment by XANA520** [comment]
Chest?
