### ISSUE TITLE
Locked out of fire temple

### ISSUE THREAD

**Issue by rbh92** [AmazingAmpharos/OoT-Randomizer#86]
I have found an issue where I am stuck behind a locked door in the fire temple.

Have acquired all 5 available chests up to this point and received only 2 keys. In order to progress in the temple, I need a third key.

This is for the door in the room above the fire/block elevator.

I have already acquired the boss key, so the temple is beatable, but is it possible I'm now locked out of acquiring an item? My settings indicate that all items should be obtainable. 

My rom settings are as follows:
All Dungeons
Open forest
Open DOT 
Place dungeon items
True random tunics
Random low health noise
Seed number: 229511447

Will play through the rest of the seed as far as I can, hopefully the rest of the fire temple contains only perishables in the chests.

**Comment by emerald000** [comment]
The boss can have a small key, which will unlock the rest of the dungeon.

**Comment by rbh92** [comment]
Can confirm that emerald000 was correct.

Thank you for your time. 

Issue closed
