### ISSUE TITLE
Slowed Gameplay

### ISSUE THREAD

**Issue by treachery13** [AmazingAmpharos/OoT-Randomizer#87]
I downloaded and opened the randomizer and it worked great, until my Windows 10 decided it needed to update randomly. I lost the save file, and now everything is slow motion including the music. The game still plays seemingly well, just really, really slowly. Reinstalling Retroarch and generating a new compressed randomizer file had no change. Any thoughts on what could be going on?

**Comment by AmazingAmpharos** [comment]
Sorry this is insanely late, but it sounds like your emulator is lagging badly.
