### ISSUE TITLE
Idea for computer vision and communicating item progress to trackers

### ISSUE THREAD

**Issue by wbern** [AmazingAmpharos/OoT-Randomizer#89]
I have been experimenting a little bit with using opencv to detect frames in OoT.

I have found that the performance doing this is just fine, but not having enough spare time to implement something like an auto splitter, I have been thinking about smaller applications.

Today it struck me that OoT rando is becoming pretty big, and watching a lot of streamers play I see they struggle a little with the trackers they use. While it is likely to become less and less of an issue after this initial hype burst, I was contemplating on whether we could somehow make it easier for users and the tracker developers as well.

My sort of main idea is to let the game output simple color-coded boxes at the bottom right of the screen when items are retreived, where they in some way get translated to numeric values corresponding to item codes for example. Skulltulas and the like could be solved with simply more color-encoded boxes. This type of setting can be disabled by default, but even if it's on, it wouldnt be a nuisance, being small colored boxes on the bottom right of the screen.

I only see a couple of issues/working points with this whole thing.

1. Trackers will need to be able to accept arbitrary input from another tool (the computer vision tool).
2. The computer vision tool needs to be written.
2.1 color capture may vary depending on the capture card and other settings, but if we still to high contrast between the colors, ranges can be detected just fine with HSL och HSV that can be configured to plain ignore brightness and focus on hue and/or saturation instead.
3. OoT randomizer needs to have the changes as well.

Thoughts?

**Comment by ChrisMuncey** [comment]
It seems like it would be easier to use cheat engine to make an auto-tracker.. just look at the ram directly and update the tracker whenever it sees a change in the players inventory

**Comment by wbern** [comment]
@ChrisMuncey ah, I take it many people play on emulator?

**Comment by JojHeywood** [comment]
Overwhelming majority.

**Comment by wbern** [comment]
Ok, I think I'll close the issue then. Thanks for the responses.

**Comment by ChrisMuncey** [comment]
Could you implement opencv or whatever you're using to track on VC?

**Comment by wbern** [comment]
@ChrisMuncey I have personally tested OBS together with an emulator and found it to work almost perfectly.

The margins should be well enough to account for camera capture card quality reduction on a VC playthrough.

Opencv and other tools for computer vision regularly face challenges of image noise and blurriness, so there are by now numerous ways of dealing with it.
