### ISSUE TITLE
Scarecrow's Song in Gerudo Training Grounds

### ISSUE THREAD

**Issue by SpringStingray** [AmazingAmpharos/OoT-Randomizer#9]
Seed: 653763373, Medallions, Open Forest, Closed Door. PJ64 2.3.

I needed a Progressive Scale to access the Shadow Temple, inside of the Shadow Temple is both a Hookshoot Progressive Upgrade and one of the Scale Progressive Upgrades.

The other scale was inside _Gerudo Training Grounds Before Heavy Block Chest_. I couldn't complete the left side of the Training Grounds without Longshot, and the Scarecrow in Eye Statue Room wouldn't summon when standing on the platform below him. Am I supposed to be able to summon Pierre when standing below and Hookshot up?

**Comment by AmazingAmpharos** [comment]
You can complete the silver rupee room in left GTG with normal Hookshot. It's long enough if you stand square under that one target to minimize the distance the chain needs to travel. No, it's not possible (at least not supposed to be possible; with tricks you never know in this game) to summon the scarecrow from the right side branch; that scarecrow is mostly useless.
