### ISSUE TITLE
Help!! I think the seed is unbeatable :(

### ISSUE THREAD

**Issue by MaxXx93** [AmazingAmpharos/OoT-Randomizer#92]
I'm gonna start this with a simple fact, sorry for my bad english xD..

I start the run with : Medallions - Open Forest - Open Door Of Time - Place dungeons items - Only ensure seed is beatable.

So now i have all six medallions, but i don't have the fire ruby and the water sapphir of the first three dungeons.

With that, i can't have the cutscene for the ocarina of time and 1 random song.
I have three songs to find: Zelda lullaby, Storm song and the nocturn of shadow.

Still need to find: Big goron sword, hover boots, Fire and Light Arrows, 1 bottle, golden scale.

Every chests is open ( where i can go), so every hidden holes is done, same thing with the piece of hearts.

Can't have access to some holes and the frog mini-game because i don't have the song of storms.
Can't have access to Ice cavern and the temple of  shadow entrance.
Can't have access to the Bottom Of The Well ( Again the song of storm..)

I did all the mini games for POH or the upgrade original item. (the 10 ghosts for the bottle..yeah..)
The quest with all the mask ( don't have 2 stone so the guy who's running....doing something else)
The quest for the BigGoron sword ( stuck because i don't have access to Zora Domain with adult link)

The only 3 places left to learn a new song are: 
Ocarina of time cutscene ( you need 2 more stones for this).
At the end of ice cavern (but without the zelda lullaby.. never mind)
And in the cemetery ( but without zelda lullaby.. same thing)

So i need zelda lullaby for 2 song, but how can i have the 2 stones left if one of these are in the shadow temple??

So like i said, every chest possible for now is open and same thing with the holes and the PoH.

I can't finish the fire temple cause probably the key i need to finish.... the boss have it. And without the hover boots, i can't fight him.

I can't finish the water temple cause i don't have the zelda lullaby ( still beat the boss because of the longshot).

I can't have all the chests in the spirit temple because i need the zelda lullaby twice and the hover boots for a switch too).

So yeah this is pretty ugly..

I realise than i don't need everything to beat the run because i start the run with Medallions option to open ganon's castle. How i do it now without the lights arrows ?

If someone please can find something i'm going crazy !!!
( i didn't use any glitches for this run and i'm not gonna start now. It's suppose to be beatable without it) 
 
I add the seed down below and if you have ANY question go ahead!!
Thanks to everyones who will take the time to read this and help me : D

[OOT_medallions_open forest_opendoor of time_beatable only.zip](https://github.com/AmazingAmpharos/OoT-Randomizer/files/2320369/OOT_medallions_open.forest_opendoor.of.time_beatable.only.zip)

**Comment by rlbond86** [comment]
It's not unbeatable.

I ran your seed, assuming I got the settings right, the light arrows are in the Gerudo Valley piece of heart crate, you have to pick up a cucco and fly to it.

**Comment by MaxXx93** [comment]
Oh god.
this is my fault actually xD
i remember i take the cucco to fly to the PoH behind the waterfall and where you have to break the box. this PoH was one of the first i did, but the game crashed maybe 15 min after without saving and probably i forgot to do it again hahahaha. i'll double check every chest and holes but didn't recheck the PoH cause i'll knew I was suppose to had these one in gerudo valley .
i was going insane !! 
Thanks you very much.!
