### ISSUE TITLE
Trouble in the Spirit Temple

### ISSUE THREAD

**Issue by BMPerkins87** [AmazingAmpharos/OoT-Randomizer#94]
As far as I can tell, the Spirit Temple is not beatable in this save file's seed. Apparently, the key I need to open a locked door is somewhere behind that locked door. I've followed guides to ensure I've looked everywhere, but no key.

I've tried to attach my save file to this issue, but apparently the file's too big for github. So I'll put a Google Drive link here instead in case the developer or whomever wants to see for themselves and maybe make a fix at some point. I'm already at the temple and I have the warp songs for both the Temple of Time and Spirit Temple. I've been using RetroArch to play it.

https://drive.google.com/file/d/1tBOMQml46CxneYtJZMnSGljFsqU75QQo/view?usp=sharing

**Comment by BMPerkins87** [comment]
Thanks for the reply. I didn't generate a spoiler log. Maps and compasses were checked.

**Comment by flagrama** [comment]
Dropping spoiler log here: https://pastebin.com/iKTkn7G3

**Comment by BMPerkins87** [comment]
Reading through and picking up bits and pieces of what I remember, I believe this spoiler log to be accurate to my game's seed. I don't know how you did it, but that's amazing.

**Comment by BMPerkins87** [comment]
Ok. Update. Turns out it was my lack of knowledge of the game that was the issue. Apparently, there are two invisible chests in the stair hallway leading up to adult Link's fight with an iron knuckle. In my defense, I didn't have the map or compass with me at the time, but there it is. Problem solved. Thank you again, flagrama.

**Comment by flagrama** [comment]
Glad you figured it out. I definitely recommend generating a spoiler log whenever you generate a seed so you can work out these kinds of issues on your own first without needing someone to force generate one for you.
