### ISSUE TITLE
Hidden grottos should have the Stone of Agony as a prerequisite

### ISSUE THREAD

**Issue by rlbond86** [AmazingAmpharos/OoT-Randomizer#95]
People who play OoT a lot probably know the locations of all of the grottos by heart. However, many people will not have all grotto locations memorized. It would probably be a good idea to require that the Stone of Agony is accessible before allowing items to be placed in these hidden grottos.

I had a seed (closed forest) where the fairy slingshot was placed in the Sacred Forest Meadow grotto and just was thinking that if I didn't know it was there I'd be stuck.

**Comment by Niamek** [comment]
A randomizer expects you to know the game enough to finish it. You can always google for a list of secret grottos on google (there is a list on zeldaspeedruns). Ther aren't that many grottos. So it shouldn't be a big issue.

**Comment by rlbond86** [comment]
You could make that same argument about invisible chests, which the randomizer DOES ensure you can get the lens of truth for.

Perhaps the ROM could be patched to always vibrate around hidden grottos instead of checking for the stone of agony?

**Comment by CMuncey** [comment]
Most players won't be able to use the rumble feature anyway because they play on emulator. I think (though I'm not certain) that the rando does use the stone of agony as a requirement for accessing grottos because of how the hint system works. I'd have to go back and look at the logic there, but I think it does.

**Comment by AmazingAmpharos** [comment]
Yeah, while I sympathize and considered it, the reality is that most players cannot use rumble anyway (anyone playing on VC or emulator; even the handful of real N64 players would have to actually own a Rumble Pak and use it). The design logic is that it doesn't make sense to require something almost all players can't use. However, with the 3.0, I want to have some very good spreadsheets that will make it more obvious where every obscure thing is hidden that you might have to check.
