### ISSUE TITLE
Won't play on mac

### ISSUE THREAD

**Issue by NaviHater** [AmazingAmpharos/OoT-Randomizer#96]
I'm Trying to play this on Mac OSX El Capitan, and it just doesn't do anything. I've installed python 3.7. Any suggestions?

**Comment by CMuncey** [comment]
Does it give an error or anything? Is it not launching, or does the UI come up?

**Comment by NaviHater** [comment]
Well, a python window pops up, and then it just sits there. There aren’t any error messages or anything

**Comment by flagrama** [comment]
Sounds like you are opening the script in IDLE and not actually running the script.

I don't have a Mac and can't really test for myself, but you can try doing this: https://superuser.com/a/1164713

Skip step 1 as it is already done for you.

**Comment by CMuncey** [comment]
Try using a terminal to launch it.

If you don't know how to do that, here's how. If the folder isn't on your desktop, then you can just replace the path part with wherever it's located.
Use `⌘ + Space` to launch the finder thingy, then type "terminal" and press enter
type `cd ~/Desktop/OoT-Randomizer-master`
then `python GUI.py`
If that fails you can try `python3 GUI.py` or maybe `python36 GUI.py`

**Comment by NaviHater** [comment]
it's working now, and thanks to everyone who helped
