### ISSUE TITLE
Unbeatable Seed with Time/Forest Lock

### ISSUE THREAD

**Issue by ApisOryzae** [AmazingAmpharos/OoT-Randomizer#97]
In my current seed, I had Forest and Door of Time locked.  The three songs I could get as a kid are the Water, Shadow, and Light teleportation songs.  Without the song of time, I can't unlock the Door of Time, and without Lullaby, I can't open the tombstone to get Sun's Song drop.  Beating the three child temples gave me Forest, Fire, and Water medallions, so I can't get the Song of Time drop.  The only other song I can get as a child is Requiem, but that's behind the entirety of the Gerudo Fortress and Desert, which is unbeatable as a child.  I've gotten nearly every item I can think of in a vain attempt to beat it, but it seems my progress is locked behind another song.

The settings plus the seed are as follows:
![seed](https://user-images.githubusercontent.com/42761568/44701106-d486cb80-aa41-11e8-86a4-d3ed96a2403a.png)

**Comment by ApisOryzae** [comment]
Looking further down, it appears to be a duplicate issue to a few others with Song of Time being locked behind becoming an adult?

**Comment by flagrama** [comment]
Yes, it's a known logic issue with v2.0 of the randomizer and closed door. It has been fixed in the [Dev](https://github.com/AmazingAmpharos/OoT-Randomizer/tree/Dev) branch and the [TestRunnerSRL](https://github.com/TestRunnerSRL/OoT-Randomizer/tree/Dev) fork.

**Comment by Greenhero30** [comment]
So you got the songs where normaly would be: Zelda's lullaby, Saria's song and epona's song.
With the forest fire and water medaillon im pretty sure you can get the nocturne of shadow normaly if you go to kakriko village. Did you get that one?

**Comment by flagrama** [comment]
Nocturne only triggers as adult, but logic believes child can trigger it. He has Song of Time on Nocturne so he is unable to open the door of time and become an adult.

**Comment by AmazingAmpharos** [comment]
To clarify for anyone still following this, this is fixed in the 3.0 coming up.
