### ISSUE TITLE
Temple of Time Cutscene Item Glitch

### ISSUE THREAD

**Issue by Boocicle** [AmazingAmpharos/OoT-Randomizer#99]
If the forest medallion is the last medallion you obtain, when you go back to the temple of time the game will trigger 2 cutscenes; the cutscene where you normally learn the prelude of light, and the cutscene where Zelda normally gives you the light arrows. When this happens, you will learn the random song but you will never be able to get the item from Zelda. I have tried exiting and re-entering as well as resetting, but it appears that this glitch can cause the item to be unobtainable.

**Comment by AmazingAmpharos** [comment]
Sorry for the late reply but there are a few things to know here. The Light Arrow item is actually triggered from just having Shadow/Spirit medallions whereas the Prelude of Light is learned from having just Forest Medallion. The trigger areas are also non-identical (I believe the Light Arrows trigger from anywhere in the ToT whereas the Prelude of Light only triggers near the Master Sword pedestal). What most likely happened here is that you got the Light Arrow item much earlier in the playthrough, returned to the ToT to get Prelude, and were surprised you didn't get the second item that you had actually gotten earlier. This situation was specifically tested for when the LA cutscene was greatly shrunken down.
